### ISSUE TITLE
Establish a Set, Consistent, & Easy Upgrade Process

### ISSUE THREAD

**Issue by joshdmiller** [ngbp/ngbp#1]
And add information about updating to the README.

**Comment by grantlucas** [comment]
As someone new to ng-boilerplate, what is the upgrade process? For example, upgrading to the latest 0.3? Thanks

**Comment by joshdmiller** [comment]
@grantlucas That's a great question and I actually just typed that answer into the Google+ announcement I'm posting. Unfortunately, the answer is that it's manual. 

This issue is the key enhancement for the next release and so I've tried to lay the groundwork. That's the purpose behind ff5d8b5850111e84a81153798be3ca7e5e2c973f, which moved the Grunt config stuff to its own file so it won't be overwritten by future changes to the build process.

So to upgrade from v0.2 to v0.3 takes a little manual effort. It should be something like this:
1. Add v0.3 as a remote branch (you may already have it there):
   
   ``` sh
   $ git remote add ngboilerplate git://github.com/joshdmiller/ng-boilerplate
   $ git fetch ngboilerplate
   ```
2. Pull in the `build.config.js` template:
   
   ``` sh
   $ git checkout ngboilerplate -- build.config.js
   ```
3. Copy your configuration from your existing `Gruntfile.js` to `build.config.js`.
4. Pull in the new Gruntfile:
   
   ``` sh
   $ git checkout ngboilerplate -- Gruntfile.js
   ```
   
   Note that if you made any changes to your configuration beyond the variables listed in the config file, you will lose them. Be sure to take note. Use caution.
5. Update Bower dependencies by copying and pasting the `devDependencies` section. And then update them:
   
   ``` sh
   $ bower install
   ```
6. Update the Karma config to be automatically managed:
   
   ``` sh
   $ git checkout ngboilerplate -- karma/karma-unit.tpl.js
   $ git rm karma/karma-unit.js
   ```
   
   If you made any changes to Karma ports and whatnot, make sure you copy them from your old config before removing it.
7. If so desired, update your code to use uiRouter, which provides far better state management than the native `$routeProvider`. This is fairly straightforward, but is entirely manual. Checkout what it looks like [here](https://github.com/joshdmiller/ng-boilerplate/blob/master/src/app/home/home.js#L27) and be sure to read the [uiRouter docs](https://github.com/angular-ui/ui-router).
8. Move `src/components` to `src/common` as this makes its purpose more clear and eliminates confusion with Bower's use of the term:
   
   ``` sh
   $ git mv src/components src/common
   ```
9. Get rid of the now-vestigial local `grunt-html2js` task:
   
   ``` sh
   $ git rm -r grunt-tasks/
   ```
   
   Now update your code to use the new html2js module names. In `src/app/app.js`, change the module dependencies "app-templates" and "component-templates" to "templates-app" and "templates-common".
10. Update `package.json` with the new dependencies. This may have to be manual. Just copy and paste the `devDependencies` section.
11. Change the header section of `src/index,html` to match the new format:
    
    ``` html
    <!-- font awesome from BootstrapCDN -->
    <link href="http://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    
    <!-- compiled CSS --><% styles.forEach( function ( file ) { %>
    <link rel="stylesheet" type="text/css" href="<%= file %>" /><% }); %>
    
    <!--[if IE 7>
    <link rel="stylesheet" href="assets/font-awesome-ie7.min.css />
    <![endif]-->
    
    <!-- compiled CSS --><% scripts.forEach( function ( file ) { %>
    <script type="text/javascript" src="<%= file %>"></script><% }); %>
    ```
12. Run a build to ensure everything is peachy:
    
    ``` sh
    $ grunt
    ```

That should do it. Maybe.

If you're on a very old version of ngBoilerplate, there may be additional steps and these may not line up exactly. Again, _if you've done any customization, this is entirely manual._ If you run into any trouble or see that I've missed a step, post it below and I'll update this little guide. You can also ping me on Twitter [@joshdmiller](http://twitter.com/joshdmiller).

Now you have something to look forward to for v0.4. :-)

**Comment by grantlucas** [comment]
Awesome. Thanks for the detailed instructions. When I have some time in the next few days I'll attempt an upgrade and update you on how it went or if there was anything missing.

I can imagine it's tough to design some sort of upgrade path for a project like this since many will download and do some heavy alterations to meet their needs. I'll be interested to see what's developed :smile:

**Comment by grantlucas** [comment]
Just wanted to update that I finally got some time to upgrade to 0.3. Followed your instructions above and it all worked great! :+1:

**Comment by joshdmiller** [comment]
@grantlucas Awesome! I have to say I'm a little surprised it worked that easily... :-)
