### ISSUE TITLE
What is the advantage of putting all html templates into javascript?

### ISSUE THREAD

**Issue by chungwong** [ngbp/ngbp#104]
ng-boilerplate puts all templates into javascript upon grunt watch and also minifies them upon grunt compile?
I wonder what the advantage is.
Does anyone have any idea?

**Comment by bkingcis** [comment]
I suspect it would be because calling to a template would require
additional http requests, but that is just my first guess.

**Comment by joshdmiller** [comment]
@chungwong That's a good question and @bkingcis is correct. Putting all templates into a JavaScript file allows us to load the entire app in a single payload, so the UI can be very snappy from initial load. It also has the side benefit of allowing us to run ngBoilerplate apps using the `file://` protocol (where XHR operations are prohibited) so we don't need to set up a web server just to develop our app.

I'll go ahead and close this issue, but feel free to ask a followup here.

**Comment by chungwong** [comment]
Thanks @joshdmiller  and @bkingcis .
How would this approach tackle with caching problem ?
Do we manually change the name of the js/css files in index.html?

thanks

**Comment by joshdmiller** [comment]
The concatenated files should be versioned (see PR #62) so they'll have a different name with every release.

**Comment by dimsuz** [comment]
But what if I want some static pages to be held in templates and at the same time they are too big (long text data for example) for me to want them to be statically linked to my production js.
In my case they represent some static subsection of my website to which user will (probably) navigate only rarely.

So I would like to have convenient  routing of `ui-router` with urls like `templateUrl: /about/mytemplate.tpl.html', but at the same time I would like them to be loaded as xhr requests, so they do not spoil a page loading time for the rest of the website.

Is this possible or am I missing something in a whole picture? :)

**Comment by joshdmiller** [comment]
I'll opt for the corny answer: with ngBoilerplate, anything is possible. :-)

If you want to have a template load by XHR, you only need to do two things: (1) add it as an exclusionary rule to your file patterns; and (2) add it to a copy task somewhere. E.g.:

``` js
app_files: {
  // ...
  atpl: [ 'src/app/**/*.tpl.html', '!src/app/about/mytemplate.tpl.html' ],
  async_tpls: [ 'about/mytemplate.tpl.html' ],
  // ...
},

// ...

copy: {
  // ...
  tpls: {
    files: [
      { 
        src: [ '<%= app_files.async_tpls %>' ],
        dest: '<%= build_dir %>/',
        cwd: 'src/app',
        expand: true
      }
   ]   
  }
}
```

And of course it must be added to the build and compile tasks.

Also, any template in `src/assets/` will be just copied, so if it's just a block of text you could just throw it in `src/assets/`.

**Comment by dimsuz** [comment]
Wow, that is really great! Thank you Josh for such detailed answer! :) This
is just what I need!
05 ÏËÔ. 2013 Ç. 21:57 ÐÏÌØÚÏ×ÁÔÅÌØ "Josh David Miller" <
notifications@github.com> ÎÁÐÉÓÁÌ:
