### ISSUE TITLE
Why aren't some bootstrap styles in final CSS

### ISSUE THREAD

**Issue by brenthale** [ngbp/ngbp#11]
Hi,

I'm really liking ng-boilerplate.  I'm a total newbie to angular and all the technogies you are using, but really like them.

As I'm trying to modify things I took some code from a JSFiddle (http://jsfiddle.net/bgrimes/58wqH/) that helps the user walk through a wizard.  It is using some styles from twitter's bootstrap project which it looks like your project uses.  The style is "form-horizontal" and I can see it in both bootstrap.css and bootstrap-responsive.css.   But when it builds I don't see that particular style in the final dist/assets/ng-boilerplate.css.   I can see parts of bootstrap.css in the final version but not the ones I was hoping to use.  

Would it be getting minimized out for some reason?  I just put the following in the index.html file to test that theory.

<form class="form-horizontal">
    This is a test of stuff.
</form>

But it still didn't put it in final CSS file.   I had code like that in some new pages I was playing with.  The new page I've added (and can see it getting loaded) is below.

Any ideas why not all of the bootstrap.css styles are in the final css?

Thanks,
Brent

```
<div class="row-fluid">
    <h1 class="page-header">
        Genealogy Charts
        <small>Descendency Charts.</small>
    </h1>

    <form class="form-horizontal">

        <ul class="nav nav-tabs">
            <li ng-repeat="step in steps" ng-class="{active: $index==getCurrentStepIndex()}">
                <a href="javascript:void(0)" ng-click="goToStep($index)">{{step}}</a>
            </li>
        </ul>
        <div ng-switch on="selection">

            <!-- First Step -->
            <div ng-switch-when="Step 1: Team Info">
                <h1>Step 1</h1>
            </div>

            <!-- Second Step -->
            <div ng-switch-when="Step 2: Campaign Info">
                <h1>Step 2</h1>
            </div>

            <!-- Third Step -->
            <div ng-switch-when="Step 3: Campaign Media">
                <h1>Step 3</h1>
            </div>
        </div>
        <div class="clearfix"></div>
        <ul class="pager pull-left">
            <li class="" ng-class="{disabled: !hasPreviousStep()}">
                <a href="javascript:void(0);" ng-click="decrementStep()">&larr; Previous Step</a>
            </li>
            <li class="" ng-class="{disabled: !hasNextStep()}">
                <a href="javascript:void(0);" ng-click="incrementStep()">Next Step &rarr;</a>
            </li>
        </ul>
        <div class="pull-right"><button style="margin:20px 0;" class="btn btn-success">Confirm and Register</button></div>
        <div class="clearfix"></div>
    </form>


</div>


```

**Comment by brenthale** [comment]
I figured it out.

I didn't understand how LESS works.  I edited the 'main.less' file and added the following line to it:

@import '../../vendor/twitter-bootstrap/less/forms.less';   

then the form.horizontal shows up in the final CSS file.

Sorry for bothering you.
Brent

**Comment by joshdmiller** [comment]
Yep, no problem. This was just to minimize the file size a little bit. Why include styles we don't need, right? 

But...this isn't in the README for the `src/less` directory. No wonder you were a little confused! I'll add that to the "to do" list.
