### ISSUE TITLE
How to move all grunt/bower staff (but for /src and /vendor) into it's own subdirectory?

### ISSUE THREAD

**Issue by bbshopadmin** [ngbp/ngbp#110]
I would like to move all files and folders, besides the src and vendor folders, to a single boilerplate folder.

boilerplate/ (<- all grunt/bower related files here)
src/
vendor/

After running build/compile it would look like this

bin/
build/
boilerplate/ (<- all grunt/bower related files here)
src/
vendor/

Issues with build.config.js:
build_dir: '../build',
compile_dir: '../bin',
vendor_files.js (<- particular problematic)

Many pathes aren't correct after changing these vars/file pathes. I tried to adapt base pathes/cwd in the Gruntfile.js, but failed. What i'm doing wrong?

It would be nice to have an simple and flexible path system.

**Comment by joshdmiller** [comment]
ngBoilerplate is meant to have very flexible paths, but within limits. Grunt is intended to work from the root directory of a project and so ngBoilerplate uses that as an assumption.

You should be able to move the Karma as well as the build configuration files to a subdirectory and you should be able to move around anything else you want to, but `Gruntfile.js` and `package.json` will probably need to stay in the root directory where they belong. Also remember that all paths are relative to `Gruntfile.js`.

What's your use case for moving `Gruntfile.js`?

**Comment by bbshopadmin** [comment]
My idea is to have a clearer root folder and put all config/build stuff into a dedicated folder, so that also the <code>node_modules</code> folder would be in it.

**Comment by joshdmiller** [comment]
Unfortunately, this goes against the recommended way to use Grunt and Node. Out of the box, it needs to function with a "convention over configuration" approach. I'm also not sure how to make it work that way.

If you have an idea how to implement this well - as an option - I'd be happy to consider a PR. But as it stands, this is a corner case that goes against the underlying software's wishes.

I'm going to close this issue, but again feel free to submit a PR and we can take it from there.
