### ISSUE TITLE
Grunt Watch hanging after initial run

### ISSUE THREAD

**Issue by grantlucas** [ngbp/ngbp#114]
After the recent upgrade to 0.3, `grunt watch` starts up properly but further file changes hang the build process at Karma.

Immediately after a file change, the following shows up in the watch output

> Running "karma:unit:run" (karma) task
> [2013-08-12 21:51:11.652] [DEBUG] config - Loading config /build/karma-unit.js

If I let it run I eventually get

> Fatal error: socket hang up
> Completed in 120.818s at Mon Aug 12 2013 21:53:11 GMT-0400 (EDT) - Waiting...

**Comment by bkingcis** [comment]
Grant,

I suspect this is similar to issue #37
https://github.com/joshdmiller/ng-boilerplate/issues/37

Still an issue for me as well.

**Comment by maku** [comment]
Yeah, I have the same problem

**Comment by grantlucas** [comment]
Thanks @bkingcis, Will take a look at that issue and see if any of the solutions work for me.

Closing in favour of following #37 since it's the same issue.
