### ISSUE TITLE
Support to angular 1.2.x

### ISSUE THREAD

**Issue by cavarzan** [ngbp/ngbp#116]
I know that the `angular 1.2.0rc1` has been just released. But I would like to know is this project will have support for this version soon or the best approach is to wait for a stable release in the next few months.

As I see and test, there is a few modifications in bower.json and now we need to include ngRoute as dependency for the app to be compatible with this version, this is necessary because now ng-route has a separated module.

[Changelog](https://github.com/angular/angular.js/blob/master/CHANGELOG.md)

**Comment by joshdmiller** [comment]
@cavarzan Well you jumped right on that, didn't you? :-)

The short answer is yes - ngBoilerplate will absolutely support 1.2 as soon as we feasibly can. Here's the longer answer:

This may be a bit of work and may not be possible to occur immediately; we rely on Bower to deliver AngularJS but the new version isn't there - in fact, the unstable (1.1.x) branch doesn't even have the separate modules available on Bower, forcing us to use the stable (1.0.x) version - which blows. I'm not sure I'd be comfortable publishing the 1.2 version to master until it is available on Bower, which may be as long as a couple months. :-/

If you're eager for the support, by all means make it happen and submit a pull request. If there are some temporary workarounds (like including AngularJS manually) then we can put it on a separate `ng1.2` branch so the more adventurous users can dive right in. Otherwise, I'll probably get to it in a few weeks - but no guarantees.

**Comment by cavarzan** [comment]
OK! 
The 1.2.0rc1 release is already supported by bower, provided by the official angular-bower projects. 
Can you create the 1.2.0rc1 branches? In this case I can fork it and create a pull request with these modifications.

`https://github.com/angular/bower-angular`
`https://github.com/angular/bower-angular-resource`
`https://github.com/angular/bower-angular-mocks`
etc...

Thanks in advance.

**Comment by 0x6a68** [comment]
Just for the records here are some issues which have to be resolved, before switching over to Angular 1.2.0 (rc):
- yearofmoo/ngMidwayTester#6
- angular-ui/ui-router#320

**Comment by joshdmiller** [comment]
You guys rock!

I created the new branch for anyone who wants to work on 1.2 support: https://github.com/joshdmiller/ng-boilerplate/tree/ng1.2wip. Feel free to submit a PR for any changes that need to be made; it's okay to make them incrementally.

**Comment by 0x6a68** [comment]
:+1:

**Comment by cavarzan** [comment]
I change a little things to support 1.2.0 and created the pull [126](https://github.com/joshdmiller/ng-boilerplate/pull/126).

Since boilerplate doesn't use ng-route (it uses ui-route) and angular-animations, we don't need to put these dependencies in the project.

**Comment by jdhiro** [comment]
Hm, 1.2 has been out for a long time now and it doesn't look like this has been touched. Is this project still going?

**Comment by PaulL1** [comment]
jdhiro: similar question answered in #221, in short the project is active, but is undergoing a substantial replatform to make it much easier for a developer to upgrade and extend ngbp within their project.  That's diverting a bit of attention.  I've successfully run ngbp with 1.2, it really isn't much of a change - basically just upgrading angular to 1.2 works.  Notes in #221 on that too.

**Comment by jdhiro** [comment]
Thanks @PaulL1! I've decided to get this current project rolling with yeoman's angular-generator while kinks get worked out. I wish these two projects were better aligned.

**Comment by amergin** [comment]
Is there a timeframe for upgrading Angular and other relevant packages? I could really use newer versions of Angular/Angular-ui/Bootstrap, but I am unsure how to update these without messing up my project directory.

**Comment by PaulL1** [comment]
I'm actually doing this upgrade myself now on my project.  NGBP isn't all that tied to angular versions, most of what it does is just build scripts.  Really only the sample app is fussy about versions.  I'm in the middle of upgrading to angular 1.3, bootstrap 3.0 etc with no real issues as yet.  I'll advise once I finish and the actual versions I've gone to.  At present, my bower.json file looks like:

  "devDependencies": {
    "angular": "~1.3",
    "angular-mocks": "~1.3",
    "bootstrap": "3.1.1",
    "angular-bootstrap": "~0.10.0",
    "angular-ui-router": "~0.2",
    "angular-ui-utils": "~0.1",
    "angular-resource": "~1.3",
    "angular-grid": "~2.0.7",
    "angular-cookies": "~1.3",
    "angular-translate": "~2.0.0",
    "angular-translate-loader-partial": "~2.0.0"
  },

And then I ran bower update

**Comment by PaulL1** [comment]
I think the key issue is that bootstrap 3.1.1 uses less 1.4 syntax, in particular the "&extend" command.  Recess doesn't support this, and it looks like recess is essentially deprecated since the twitter folks have stopped using it for bootstrap internally.  I think that means we'll need to move across to grunt-less instead.  Pull request #225 provides this functionality.

**Comment by juanmac** [comment]
@PaulL1, so switching to grunt-contrib-less as it shows #225 and changing `package.json` as you suggest will work fine?

**Comment by PaulL1** [comment]
I'm still in the middle of it, it's not working fine as yet, but I hope that it will.  :-)

**Comment by joshdmiller** [comment]
You'll also have to add ngRoute as a dependency in your app.js since it is a separate module now. Other than that, the switch is trivial.

**Comment by cheekybastard** [comment]
@jumc  #225 switch to grunt-contrib-less works fine

**Comment by PaulL1** [comment]
Yeah, I think my upgrade has gone fine.  Angular-translate is fully broken, but that's not related to ngbp.

**Comment by mbroadst** [comment]
hey, is there in fact a branch where angular has been updated to 1.2? Updating the bower file and running bower update works just fine, but the karma tests fail for me. I noticed that @cavarzan has a PR updating the version, but it seems to have languished over the past couple of months. If you can tell me which branch I should target I have no problem putting together a more comprehensive PR (if one is needed), just need to know how to fix that karma test.

**update** okay the karma fixes were pretty easy, just moving 'ui.route' => 'ui.router', and 'ui.state' => 'ui.router.state', respectively

**Comment by 0x6a68** [comment]
we are using a fork of this boilerplate, i made kind of "spring cleanup". it could help you get started with upgrading. https://github.com/neoskop/ng-boilerplate/commit/80c36f764ee507cddadea89fe4ff0b400e0077af

**Comment by mbroadst** [comment]
@johannestroeger thanks!
@joshdmiller is there interest in upgrading these things for the 0.3.x release? I see there is work on 0.4, but it seems unfinished

**Comment by mbroadst** [comment]
I've created this pull request (https://github.com/ngbp/ngbp/pull/232), as a proposed update to a new version 0.3.2 of ngbp, updating angular in the process

**Comment by amergin** [comment]
@PaulL1: what modifications are needed for Bootstrap 3 in the less compilation? The less files have different names at least in the new version, so I'd need to adjust main.less at least?

Edit: I see errors like:

> > Parser error in vendor/bootstrap/less/mixins.less
> >      643.   padding-right: (@grid-gutter-width / 2);
> >      644.   &:extend(.clearfix all);
> >      645. }
> > 
> > Parser error in vendor/bootstrap/less/type.less
> >      209.       margin-left: @component-offset-horizontal;
> >      210.       &:extend(.clearfix all); // Clear the floated `dt` if an empty `dd` is present
> >      211.     }

**Comment by amergin** [comment]
Ah, seems I need to use Gruntfile.js that does not use recess https://github.com/ngbp/ngbp/pull/225. With the new file in place the less compilation at least does not give errors.

**Comment by ashwini162606** [comment]
hello , i want to upgrade  angular 1.1.5 to angular 1.2.x  , may any one help me out..

**Comment by joshdmiller** [comment]
Sorry - this issue should be closed. The most recent version supports 1.2. I recommend users upgrade, but you can certainly check out the diff and change the version yourself, if you'd prefer.
