### ISSUE TITLE
Support performance optimized templating

### ISSUE THREAD

**Issue by raDiesle** [ngbp/ngbp#118]
Hi,

in ng-boilerplate html2js is used to combine all code into one file.
I am wondering, if a productive application needs to have some optimizations,
such as the usage of ng-init,ng-cloak, combination of server-side rendering, flicking issue & SEO, prefetching/lazy loading.

How do you think about it, something for ng-boilerplate to answer?

**Comment by joshdmiller** [comment]
@raDiesle Good questions. I think anything too specialized is beyond the scope of ngBoilerplate, so things like server-side rendering and SEO wouldn't be something for it to solve.

But I'm all about optimizations - especially in the tricky areas. Are there specific things you have in mind that you think would make a good addition to a generic kickstarter?

**Comment by joshdmiller** [comment]
I'll go ahead and close this. If the conversation picks up again, I'd be happy to reopen it.
