### ISSUE TITLE
how to change build_dir and compile_dir ?

### ISSUE THREAD

**Issue by chungwong** [ngbp/ngbp#125]
I found there are <%build_dir %> and <%compile_dir%> variables in gruntfile.js.
I would like to test the possibility of changing the destination for both build and bin directories. 
I am not very familiar with grunt configuration and I got no idea where I can declare the path for these variables.
Does anyone have an idea?
thanks

**Comment by chungwong** [comment]
It looks like I have found the answer for it. It is located in build.config.js. However, it is not doing what I am expecting.
What I am trying to do is to move the build/bin directories out of ng-boilerplate, say, put them one directory level up(../ng-boilerplate/bin).

Also, is it possible to prefix the script/style tag? say changing 

``` html
<script type="text/javascript" src="src/app/app.js"></script>
```

 to

``` html
<script type="text/javascript" src="i/am/a/prefix/src/app/app.js"></script>
```

thanks

**Comment by joshdmiller** [comment]
@chungwong The build paths are meant to be configurable and you're correct about where to change them. While I have not anticipated building in a higher directory, I don't see why it wouldn't work. If you do something like:

``` js
build_dir: '../build',
```

That should work. If it doesn't, can you be more specific about what occurs or doesn't occur?

To your other question, the script paths are set as what they are in the filesystem, but you can give them all a prefix if you edit `index.html` to something like this:

``` html
<!-- compiled scripts --><% scripts.forEach( function ( file ) { %>
<script type="text/javascript" src="i/am/a/prefix/<%= file %>"></script><% }); %>
```

**Comment by chungwong** [comment]
Thanks Josh

**Comment by chungwong** [comment]
Hi Josh,
changing 
  build_dir: '../build',
gave me error:
Running "clean:0" (clean) task
  Cleaning "../build"...Warning: Cannot delete files outside the current working directory. Use --force to continue.

I did a search and looks like I can add a force option to clean, but I couldn't find a spot for me to add the option.
Do you have any idea?
Thanks

**Comment by joshdmiller** [comment]
You'd have to add it to the `clean` config in `Gruntfile.js`. See [here](https://github.com/gruntjs/grunt-contrib-clean).

That said, this doesn't sound like a great idea. Using `force` means that you won't get any of the other protections, so you could accidentally delete things you don't mean to. My vote would be to not use `../build/` but rather a directory inside the current working directory. If it's just a matter of cleanliness, the risk is probably not worth the reward.
