### ISSUE TITLE
Failed to load resource	file:///C:/Users/.../src/%3C%=%20file%20%%3E:0

### ISSUE THREAD

**Issue by chennoam7** [ngbp/ngbp#129]
Hi,

First thank you for your great work.
I did everything as you wrote in your instructions, however when I run the application I get Failed to load resource    file:///C:/Users/chenn/WebstormProjects/ng-boilerplate/src/%3C%=%20file%20%%3E:0

How can I fix it.

Thanks in advance.

Best regards,
Chen

**Comment by joshdmiller** [comment]
I am not a Windows expert and so will likely not be much help here, but can you post your `package.json` file and a screenshot of the error?

**Comment by chennoam7** [comment]
Hi,

I didn't change any package file, and I can pass over the whole project.
Actually I've downloaded the ng-boilerplate, extracted the file, ran the quick start instuctions and that's it.
When I open the project folder using webstorm and try to debug index.html I get the error.

Thank you,
Chen

**Comment by PaulL1** [comment]
It looks suspiciously like you haven't run grunt build to get a set of code in the build directory.  If everything were working correctly I think you would have opened index.html from the build directory, and it should have no references to anything in the src directory.  My reading of your error is that it's looking for something in the src directory.

Which file did you open in your browser?

**Comment by chennoam7** [comment]
Hi,

First I'm sorry for my lack of experience in the open source world and
environment; my experience is only in windows and visual studio.
I understand that it's better to use webstorm for front end website
development.
I read alot regarding best ways to start an good angular project and found
your ng-boilerplate with good reviews.

All I wanted to do is downloading your boilerplate, be able to kick start
and be able to debug the sources using webstorm with a well defined best
practices project.

Best regards,
Chen

2013/8/26 PaulL1 notifications@github.com

**Comment by joshdmiller** [comment]
@chennoam7 Without a special plugin or defined build process, you can't use the debug tools inside Webstorm (or any other IDE). What @PaulL1 is referring to is the build process that comes with ngBoilerplate, which is powered by [Grunt](http://gruntjs.com). You can develop in Webstorm, but you still need to run Grunt from a terminal/console. The README has a lot more detail, but you should be looking at something like this:
1. Open a terminal and `cd` to the right directory.
2. Run `grunt watch` to trigger the build process.
3. Open `build/index.html` in your browser. This is your built file.
4. Use Webstorm to make any and all changes you like; when you save any file, Grunt will automatically rebuild the necessary files.
5. Refresh your browser.

Perhaps someone with some Windows experience can provide something in more detail; if as a pull request, I would be happy to add it to the README. :-)

**Comment by chennoam7** [comment]
Hi Josh,

Thank you very much for the important details :)

Best regards,
Chen
