### ISSUE TITLE
Organizing projects with client side and server side components

### ISSUE THREAD

**Issue by jrootham** [ngbp/ngbp#131]
I have a project that has both client side and server side components with a lot of code common to both.

I am thinking I want closely coupled development and a loosely coupled system.  That is, all the tests run every time I change something on either side, and the components communicate via a REST API.  In this case the server side components are node.js items.

My thinking is a dev tree like this:

project
   client
      vendor
      src
         app
         common
         project-common
         less
   server
       server-common
       vendor
       component1
        ...

Would this work?  Assuming changes to Grunt.
Is it a good/bad idea?  Why?

Also:  Consensus seems to be Mocha for testing  node.js.  I assume moving to Mocha for the client side is a matter of adjusting karma-unit.tpl.js.  Is this true?

Thank you.

**Comment by ElliotPsyIT** [comment]
This is an interesting topic for discussion.  But since it's not specifically an ngBoilerplate issue, you might consider posing the question to the google group @joshdmiller set up for just such a discussion.

https://groups.google.com/forum/#!forum/ng-boilerplate

**Comment by jrootham** [comment]
Thanks @fielstem, I have posted to the Google group.
