### ISSUE TITLE
Cant reach to index.html

### ISSUE THREAD

**Issue by TomerAvni** [ngbp/ngbp#133]
Sorry for the ignorant question, but I can't seem to reach the index.html after the "delta" was loaded. When referring to http://localhost:38774/build/index.html I keep getting {"error":"not_found","reason":"no such route"}.
The port stated above is defined on the gruntfile and was changed to avoid conflict with another grunt using the default port:
delta: {
      options: {
        livereload: 38774
      },

Any thoughts on this?

**Comment by daverodz** [comment]
I have the same problem and can't use boilerplate :(

**Comment by joshdmiller** [comment]
Hey guys. Sorry for the delayed response. I may be misunderstanding What
you're trying to do, but you need to open the `index.html` file from the
filesystem; e.g. `file:///path/to/my/boilerplate/build/index.html`. The
port is for livereload, which works off the filesystem by activating the
browser plugin.

Let me know if I misunderstood your problem.

**Comment by daverodz** [comment]
Ah ok but what is the grunt watch thing?
For example if I run the initial instructions it stays in delta task
waiting....
After I run that and I make changes in the code and have the index opened
in the file system, Will I be able to see the changes in real time?

What I'm doing is the initial instructions until grunt watch and then open
a browser with the port and write build/index.html.  This is where I can't
find the index.html.

I know you probably receive this a lot and thank you for your time to
respond :)

**Comment by joshdmiller** [comment]
I'm happy to help. Perhaps after we straighten this out, you can suggest
ways to improve the docs to make it clearer for others. :-)

You are using the grunt watch correctly, but you still open it from the
filesystem. When you make a change, grunt will regenerate the relevant
files (including the HTML file if necessary) and you have two options for
seeing the changes in the browser. (1) you can hit "refresh", or (2) you
can enable live reload, which will do it for you.

Live reload uses a browser plugin that must be installed and enabled. The
readme file explains how to do this.

Does that make sense?

**Comment by daverodz** [comment]
That's great! I was doing it wrong the whole time :D... I was trying to
browse localhost:proxy/build/index.html....

Thanks for all the help and will proceed into playing with the project and
creating my prototype.  I will see what I could add into the read me
instructions for angular and js noobs like myself.

Thanks again for the support and hope the best for the project!

-David.

**Comment by lashex** [comment]
I ran into this same confusion. Perhaps instead of the `README.md` doc stating "Finally, open `build/index.html` in your browser." it could say "Finally, open `build/index.html` as a file from the filesystem in your browser."

That phraseology seems much more clear to my brain.

**Comment by joshdmiller** [comment]
Okay, fair enough. I changed the docs (see 3344671) and it will be in the next release.
