### ISSUE TITLE
First Time running the project it hangs in "Running "recess:build" (recess) task"

### ISSUE THREAD

**Issue by daverodz** [ngbp/ngbp#134]
Hello Guys,
I really want to use this project to my own but I keep having problems when trying to run the project :( so please help?
Right now I did everything successfully from the installation instructions except to the part of Grunt Watch where my process stops here:

Running "recess:build" (recess) task

> > '../../vendor/bootstrap/less/reset.less' wasn't found.
> > Warning:  Use --force to continue.

Aborted due to warnings.

And when I used --force, I had problems with firefox and it ended up hanging here:
Running "delta" task
Waiting...

The firefox errors are:
Firefox 23.0.0 (Ubuntu) ERROR
    ReferenceError: angular is not defined
    at /home/ac3flash0rp/ng-boilerplate/vendor/placeholders/angular-placeholders-0.0.1-SNAPSHOT.min.js:1
Firefox 23.0.0 (Ubuntu) ERROR
    ReferenceError: angular is not defined
    at /home/ac3flash0rp/ng-boilerplate/build/templates-app.js:1
Firefox 23.0.0 (Ubuntu) ERROR
    ReferenceError: angular is not defined
    at /home/ac3flash0rp/ng-boilerplate/build/templates-common.js:1
Firefox 23.0.0 (Ubuntu) ERROR
    ReferenceError: angular is not defined
    at /home/ac3flash0rp/ng-boilerplate/src/app/about/about.js:1
Firefox 23.0.0 (Ubuntu) ERROR
    ReferenceError: angular is not defined
    at /home/ac3flash0rp/ng-boilerplate/src/app/app.js:1
Firefox 23.0.0 (Ubuntu) ERROR
    ReferenceError: angular is not defined
    at /home/ac3flash0rp/ng-boilerplate/src/app/home/home.js:15
Firefox 23.0.0 (Ubuntu) ERROR
    ReferenceError: angular is not defined
    at /home/ac3flash0rp/ng-boilerplate/src/common/plusOne/plusOne.js:1
Firefox 23.0.0 (Ubuntu): Executed 0 of 0 ERROR (0.123 secs / 0 secs)
Warning: Task "karma:continuous" failed. Used --force, continuing.

Please help and let me know what to do please!!! I really want to use this to get started into agunlar js :)

Thanks for reading this and for the help in advance.
Regards,
David Rodriguez.

**Comment by davedbase** [comment]
Bower changed the directory that it installs components. Follow this stackoverflow article: http://stackoverflow.com/questions/14079833/how-to-change-bowers-default-components-folder but make sure the directory is "vendor".

**Comment by daverodz** [comment]
Thanks alot and I will take a look and let you know.
