### ISSUE TITLE
Minifying/Uglifying ngBoilerplate issues

### ISSUE THREAD

**Issue by tschofen** [ngbp/ngbp#145]
Compile fails on my app during 'uglification'.

I noticed that the example app.js file doesn't use the 'module style' to avoid uglification issues which according to http://docs.angularjs.org/guide/di is needed to minify the code. 

``` javascript
.controller( 'AppCtrl', function AppCtrl ( $scope, $location ) {
  ...
})
```

Is ngBoilerplate doing something special to avoid having to write in 'module style'?

Any suggestions on how to approach finding the issue?

Thanks in advance.

**Comment by joshdmiller** [comment]
Yes, we use ng-min to do that step for us, pre-minification. There is a
known issue with ng-min and resolve blocks in routes, where the array
syntax is required still, but other than that it should work flawlessly.

Can you elaborate on your problem?

**Comment by tschofen** [comment]
Changing resolves to array notation seems to solve the issue.

Thanks for the quick response.
