### ISSUE TITLE
Add Grunt task to support IE-only scripts

### ISSUE THREAD

**Issue by tschofen** [ngbp/ngbp#148]
In order to get angular to work with IE8 I need to load json2.js. Unfortunately, it errors during the build process. ( I tried json3.js and minified version too). 
The process: `Running "jshint:src" (jshint) task` stops with too many errors.

Is there a way to exclude specific files so they don't get processed and remain standalone files?

Thanks in advance.

**Comment by joshdmiller** [comment]
Vendor files should be in `vendor/`.

Things in `vendor/` get concatenated and minified, but they do not get linted. Files in `src/app/` and `src/common/` are linted, tested, concatenated, and minified.

**Comment by tschofen** [comment]
Not quite what I'm after. The IE8 files are conditionally included. If I put them into the vendor directory they get included for the build.  

Looks like I need to add an IE8 specific task to the grunt file.

**Comment by joshdmiller** [comment]
That's probably a good idea; there's already an issue for IE conditional stylesheets: #88. I changed the title of this issue to reflect what you want to do.

In your case, you can also put the JS file in `src/assets/`, where it will be copied by the build but not included in it. This is _not_ what would need to be done long-term as there may be app-specific IE-only files too.

If you add an IE-specific grunt task, a PR would be awesome. :-)

**Comment by tschofen** [comment]
False alarm. I must have somehow removed the exclusion of the asset files from the build.config.js file, hence the linting tried to include my js files from the assets folder
In order to accommodate old browsers, all that's needed is putting the JS/Css files into assets and using conditional comments to include them in the index.html file. 

A simple example that would include a file from assets folder as well as other IE8 specific fixes into the html for <= IE8.

``` html
<!--[if lte IE 8]>
    <script src="/assets/json2.js"></script>
    <script>
        document.createElement('accordion');
        document.createElement('accordion-group');
        document.createElement('panel');
        document.createElement('ng-pluralize');
      </script>
<![endif]-->
```

Thanks again for the quick responses.
