### ISSUE TITLE
Why not base that on HTML5 Boilerplate ?

### ISSUE THREAD

**Issue by abourget** [ngbp/ngbp#15]
It's a boilerplate, but not based on the most used boilerplate :)

HTML5 Boilerplate has a lot of great features, Modernizr integration, and several gotches dealt with.

Why wasn't it used as a base ?

**Comment by joshdmiller** [comment]
Good question! Sorry it took me an absurd amount of time to address the question. :-(

HTML5 Boilerplate clashes a little bit. It includes jQuery support and I don't think this project should include jQuery. It also includes Normalizr, a modified version of which is already included in Twitter Bootstrap.

I also don't like their folder structure.

That said, there are some things we could pick up from HTML5 Boilerplate:
- Modernizr integration (I opened issue #29 for this)
- Google Analytics
- Default server configs

I'm going to close this as answered, but if there's something you feel is missing, please let me know!
