### ISSUE TITLE
Multi-file modules

### ISSUE THREAD

**Issue by kpgarrod** [ngbp/ngbp#152]
I have an existing project which I am trying to migrate into the ng-boilerplate folder structure. The project uses modules, but the modules are spread across a number of files.

I get 'No Module' messages, because the file that declares the module is not always loaded before the files that extend it. 

I can overcome the issue by combining files into a single file per module, but I don't necessarily want to do that.

Is there another way around the problem?

Thanks.

**Comment by joshdmiller** [comment]
ngBoilerplate is designed around having one file per module because, in addition to other benefits, it prevents these kinds of order of execution problems. I recommend refactoring your code into submodules (e.g. "myMod.mySubmod") instead.

That said, there's probably a way to get it to work, but it would almost surely be a hack. Sorry. :-(

I'll leave this open for a few days to see if anyone else has an idea.

**Comment by trussell314** [comment]
I've been running into this some too. I've got things arranged such that everything loads in the proper order but it's more by accident than anything; all my modules (with dependencies) are "declared" in my app.js which happens to load first, and the controllers and such are loaded from the files deeper in the file tree. It basically boils down to how build.config.js defines app_files.js. The globbing pulls all the 'src/*_/_.js' matches and appears to alphabetize them based on the full path+filename. It's possible to make those wildcards more fine-grained which (I believe) has the desired effect on how the grunt concat task builds the single js file in the 'compile' task. However, the karma run in the 'build' task runs against the individual files, not the the concatenated js file and so it doesn't recognize the order you declare; the 'No Module' errors still appear even though the final output is fine.

What might work to fix that (though I'm not sure how wise it is) would be to have an intermediate karma task which operates on the compiled (concatenated) js so that karma runs on the same js that ultimate ends up being deployed from the compiled bin directory. In that scenario, the grunt process would go build -> compile -> test -> copy to bin. This would mimic maven's build lifecycle of validate -> compile -> test -> package (shortened here for relevance/brevity). While adding some complexity, this does have the advantage of running karma against the exact code that will be deployed.

**Comment by kpgarrod** [comment]
Thanks for the input. I see the benefits of using single-file modules and
will probably refactor accordingly.

Another related issue though, is that I am using factories to access
external resources. These factories will be used in multiple projects and
multiple modules within a project. So, in the ng-boilerplate structure, I
see that these factories should live in 'common', but it would be
cumbersome to have a module for each factory. Should I lump them all
together in one module? That also doesn't seem quite right.

The readme suggests that 'common' modules should be cut-and-pasteable. That
sounds good but I'm not sure how to keep them in sync.  I tried using a git
submodule to include the common modules but found that to be a real
nuisance. Is there a better way?

On 24 September 2013 16:21, trussell314 notifications@github.com wrote:

> I've been running into this some too. I've got things arranged such that
> everything loads in the proper order but it's more by accident than
> anything; all my modules (with dependencies) are "declared" in my app.js
> which happens to load first, and the controllers and such are loaded from
> the files deeper in the file tree. It basically boils down to how
> build.config.js defines app_files.js. The globbing pulls all the
> 'src/*_/_.js' matches and appears to alphabetize them based on the full
> path+filename. It's possible to make those wildcards more fine-grained
> which (I believe) has the desired effect on how the grunt concat task
> builds the single js file in the 'compile' task. However, the karma run in
> the 'build' task runs against the individual files, not the the
> concatenated js file and so it doesn't recognize the order you declare; the
> 'No Module' errors still appear even though the final output is fine.
> 
> What might work to fix that (though I'm not sure how wise it is) would be
> to have an intermediate karma task which operates on the compiled
> (concatenated) js so that karma runs on the same js that ultimate ends up
> being deployed from the compiled bin directory. In that scenario, the grunt
> process would go build -> compile -> test -> copy to bin. This would mimic
> maven's build lifecycle of validate -> compile -> test -> package
> (shortened here for relevance/brevity). While adding some complexity, this
> does have the advantage of running karma against the exact code that will
> be deployed.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ngbp/ng-boilerplate/issues/152#issuecomment-25008132
> .

## 

Keith Garrod

Tel: +27-83-3000-988
Fax: +27-86-5757781

**Comment by alex6o** [comment]
We are planning a larger project based on AngularJS and we are very excited about the feature-based project structure of ngBoilerplate. We have also noticed this single file "limitation" that all services, directives etc. have to be in one file, but wouldn`t it be possible to introduce folders with reserved names (like e.g. views, directives etc. see also the corresponding yo angular generator structure) which are concated before the module files.

**Comment by joshdmiller** [comment]
@trussell314 It's probably a good idea to run unit tests on the compiled source before distribution, but not as a part of development. The reasons for separate build and compile directories are performance and reporting. The build simply copies files, which occurs on the order of milliseconds; when we add the compile functions like concatenation and minification, we move from milliseconds to seconds. That is, in the watch, on every file change, you would have to wait four or five seconds for the unit tests to complete. The community judged previously that was too long to wait - and I tend to agree. Also, if there's an error in your code and your test fails, Karma will report the concatenated and minified point of error, which will be very unhelpful when it comes to finding what went wrong!

@kpgarrod Cut-and-paste-able is the goal, yes. However, if a piece of code is _actively_ being used and changed in multiple projects, `src/common/` is probably not the best place for it; `vendor/` may be a better choice. An independent component should be kept separately, coded separately, and tested separately. To integrate it into the several projects that use it you could use a git submodule as you said, but bower is a better choice. If your reusable package is local, then in your `bower.json`:

``` js
{
  "name": "myproject",
  "version": "1.0.0",
  "dependencies": {
    // ...
    "mypackage": "file:///path/to/mypackage.git/"
  }
}
```

When the package changes, you simply need to issue `bower update mypackage`.

However, if you work as part of a team, having a local dependency may be impractical. In that event, you could publish your package to Bower if it is non-proprietary, or you could [set up a private bower repository](http://toranbillups.com/blog/archive/2013/08/04/How-to-host-a-private-bower-registry/) if it is.

In either event, if a piece of code is being used in multiple places, I strongly advice against editing it as part of either project, but rather _only_ making changes on its own to a spec with tests.

@mrmuh Of course it would be possible to use such a structure, but this would violate the spirit and philosophy of ngBoilerplate. One file per module, one module per directive, nested modules, and drag-and-droppable folders are at the very heart of ngBoilerplate. Using folders like `views`, `directives`, and the like would go directly against this philosophy. For some more information on this structure and why we prefer them to the Yeoman generators' structure, see yeoman/generator-angular#109.

**Comment by trussell314** [comment]
@joshdmiller Good points. I don't run 'watch' so I hadn't considered the extra delay. I'll move toward single-file modules and see if I can work out the kinks I encountered previously.

**Comment by paulmelnikow** [comment]
Hi there, I'm adapting ng-boilerplate for an existing project. I really like the source code organization, though I'm integrating it with our existing build system. I needed a solution for multi-file modules and came up with something that seems to be working. In a multi-file module folder, I create an _init.js which declares the module:

```
angular.module( 'ngBoilerplate.about', [
  'ui.state',
  'placeholders',
  'ui.bootstrap'
])

;
```

And then my other .js files can do this:

```
angular.module('ngBoilerplate.about')

.controller ...

;
```

It seems like a powerful and useful convention, giving the developer a lot of flexbility about how to break up files. If Grunt's globbing does alphabetize as you say, it should work smoothly. It also has the advantage of being optional – if you have one file, you can define the module in it; if you have multiple, you reference the module and define it in _init instead.

I'll work up an example and put together a pull request if you're interested!

**Comment by cesutherland** [comment]
Maybe it's straight forward for users of ng-boilerplate to implement a client-side module wrapper when needed.  With CommonJS, assuming angular is available globally, it'd look something like:

app.js:

``` javascript
require('myModule/module.js'
```

myModule/module.js:

``` javascript
angular.module('myModule', []);
require('./directives.js');
...
```

myModule/directives.js:

``` javascript
angular.module('myModule')

.directive('myDirective', ...
```

I believe it'd be similar with AMD.

**Comment by joshdmiller** [comment]
There are some good suggestions here and, I believe, enough for users who need to use multi-file modules to find a solution. But the community consensus seems to be (and I agree) that multi-file modules are not ideal. As such, ngbp won't be supporting it right now.

I'm going to close this, but if anyone wants to submit a PR to solve for this, I'm sure we'd all be happy to review it.

**Comment by cesutherland** [comment]
@joshdmiller do you have any resources handy which discuss why multiple file modules are not ideal?

At least for the approach I describe, I do think it's something which should be implemented by a user of ngbp and not by ngbp itself.  I'm just curious about the arguments on the topic.

**Comment by joshdmiller** [comment]
@cesutherland I don't have anything handy, but I can give my thoughts. Essentially, it's two reasons:
1. It can lead to the kinds of problems reported here. :-)
2. Ease of documentation. It's a lot easier (and more predictable) to find code in files that are appropriately labelled and (as much as possible) self-contained. If one is in a file that is part of (but does not declare) a module, there is no defined method or process by which to locate the module definition. Onboarding new developers is similarly difficult.

To button this up, it's completely unnecessary. It arguably saves no time versus breaking modules into smaller ones, makes code reuse more difficult, and causes some potential headaches. So, why bother? My philosophy is that if course "A" works just fine and course "B" has some problems associated with it, we need a compelling reason at least in proportion to the problems created to choose "B" over "A". Bottom line: I don't see such a reason to use multi-file modules.
