### ISSUE TITLE
Nested templates

### ISSUE THREAD

**Issue by narkisr** [ngbp/ngbp#156]
Im trying to use a nested strucure where:

``` bash
systems/
   systems.tpl.html
   system/
        system.tpl.html
```

Iv added a glob pattern to match under app_files yet it seems that angular does not find the nested directives/template

Thanks

**Comment by joshdmiller** [comment]
You should not need to change _anything_ to use the structure you gave; that's the structure I had in mind when I created it. Without your glob addition, can you elaborate on the problem you had?

**Comment by narkisr** [comment]
The issue is that directives aren't found (I see [object object]):

``` javascript
// the module
.directive('proxmox', function() {
      return {
        restrict: 'ECMA',
        templateUrl: 'systems/proxmox.tpl.html'
      };
})

// ....


 $scope.loadSystem = function(){
    $scope.system = System.get({id:$scope.id},function(sys,resp){
      $scope.hypervisor = _.filter(['aws','proxmox','vsphere'],
                              function(a){return sys[a]!=null; })[0];
      $scope.hypervisorData = sys[$scope.hypervisor];
      $scope.headerTemplate = 'systems/'+$scope.hypervisor+'.tpl.html';
    }); 
  };
```

And the view

``` html
<div>   
  <p>   
     <div ng-include src="headerTemplate"></div>
  </p>  
</div> 
```

As you can see the template is loaded dynamically, I don't think that this has anything to do with it not working in 2 levels of nesting 

Thanks

**Comment by dearfrankg** [comment]
check in the build folder for the templates-app.js and find the correct path to the template you're after.

**Comment by narkisr** [comment]
Thanks guys, it seems to work looks like I forgot to change 

``` javascript
$scope.headerTemplate = 'systems/system/'+$scope.hypervisor+'.tpl.html';
```

**Comment by joshdmiller** [comment]
@narkisr I'm glad you solved it. But I'm a little confused by your code; you said it can't find your directive, but you're not actually using the directive - you just included a raw template with ngInclude. Was there some code missing?

**Comment by narkisr** [comment]
Initially I tried using ng-switch and directives but that didn't work so I switched to dynamic include, I do recall that I had some issue with paths but the late hour might have taken its toll ;) 

Thank you for the well balanced structure and layout, it really composes well

**Comment by joshdmiller** [comment]
I only meant that by your code the directive isn't used at all. It's irrelevant to the template problem you solved, but it caught my attention anyway.

**Comment by narkisr** [comment]
Yeap iv cleared it up, thanks

**Comment by hourback** [comment]
@narkisr Would you please tell me what else you did to configure your nested routes?  Here's my post on the subject:

https://groups.google.com/forum/#!topic/ng-boilerplate/Md2Y0-nB6fw

Thanks in advance,
Ali

**Comment by narkisr** [comment]
Hey Ali, from what I can tell in the your google groups post you did everything correct, 

The only think I change was:

``` javascript
  // build.config.js
  atpl: [ 'src/app/**/*.tpl.html','src/app/**/**/*.tpl.html' ]
```

But I suspect I didn't have too, as suggest above take a look at templates-app.js and see that the nested templates appear within it. 

Regarding refering nest modules keys they aren't nested:

``` javascript
angular.module( 'celestial.systems', [
  'ui.state', 'ui.bootstrap', 'ngResource','celestial.system','celestial.systemAdd'
])
```

As far as I can tell the entire module system has no direct relation to the location in the FS (only templates do and thats I guess part of the way the templates are converted to js). 

Hope it makes sense

**Comment by hourback** [comment]
Hey, ronen.  Thanks, that helps.

How do you define your routing?  For example, do you have a systems.js that
defines a state of 'systems' and then a route for '/systems', and then a
system.js that does the same but for a state of 'systems.system', a route
for '/systems/system', and maybe another one for '/systems/system/:id'?

-Ali

On Thu, Sep 26, 2013 at 9:11 PM, ronen notifications@github.com wrote:

> Hey Ali, from what I can tell in the your google groups post you did
> everything correct,
> 
> The only think I change was:
> 
>   // build.config.js
>   atpl: [ 'src/app/**/*.tpl.html','src/app/**/*_/_.tpl.html' ]
> 
> But I suspect I didn't have too, as suggest above take a look at
> templates-app.js and see that the nested templates appear within it.
> 
> Regarding refering nest modules keys they aren't nested:
> 
> angular.module( 'celestial.systems', [
>   'ui.state', 'ui.bootstrap', 'ngResource','celestial.system','celestial.systemAdd'])
> 
> As far as I can tell the entire module system has no direct relation to
> the location in the FS (only templates do and thats I guess part of the way
> the templates are converted to js).
> 
> Hope it makes sense
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ngbp/ng-boilerplate/issues/156#issuecomment-25216115
> .

## 

WWW        - http://www.alijnabavi.info/
OpenSocial - http://www.opensocial.org/profile/AliJNabavi
Identi.ca  - http://identi.ca/alijnabavi
Twitter    - http://twitter.com/alijnabavi
Google+    - https://plus.google.com/110570367655470385186/

**Comment by narkisr** [comment]
I think that routing is open to any scheme you like, in my case:

/system/:id 
/systems

Im quite sure I could have nested them in same fashion you suggested
