### ISSUE TITLE
After running grunt, I get ... Fatal error: Cannot read property 'red' of undefined

### ISSUE THREAD

**Issue by nuweb** [ngbp/ngbp#16]
I get the following error when running grunt.
Running "recess:build" (recess) task
Fatal error: Cannot read property 'red' of undefined

Here's the entire log:

grunt
Running "clean:0" (clean) task

Running "html2js:app" (html2js) task

Running "html2js:component" (html2js) task

Running "jshint:src" (jshint) task

> > 16 files lint free.

Running "jshint:test" (jshint) task

> > 4 files lint free.

Running "jshint:gruntfile" (jshint) task

> > 1 file lint free.

Running "jshint:globals" (jshint) task

> > 0 files lint free.

Running "test:unit" (test) task
INFO [testacular]: Testacular server started at http://localhost:9018/
INFO [launcher]: Starting browser Firefox
INFO [Firefox 16.0 (Mac)]: Connected on socket id GQmF8UwyBM1c-bETSCFe
.......
Firefox 16.0 (Mac): Executed 7 of 7 SUCCESS (0.224 secs / 0.052 secs)
Running cmd

Running "concat:dist" (concat) task
File "dist/assets/ng-boilerplate.js" created.

Running "concat:libs" (concat) task
File "dist/assets/libs.js" created.

Running "uglify:dist" (uglify) task
File "dist/assets/ng-boilerplate.min.js" created.
Uncompressed size: 82592 bytes.
Compressed size: 9520 bytes gzipped (48083 bytes minified).

Running "recess:build" (recess) task
Fatal error: Cannot read property 'red' of undefined

**Comment by joshdmiller** [comment]
`grunt-recess` can be quite a pain when it comes to error reporting. This should mean there's an error in your LESS code. I remember getting this when an import couldn't be found. Try running `lessc` on the file manually to see if you get a helpful error.

In another project I swapped `grunt-recess` for `grunt-less` and just gave up on linting. I might do that here.

**Comment by nuweb** [comment]
Thanks, will try it out.

**Comment by nuweb** [comment]
Just to mention, I got the error without making any changes to the repo. I did a clone, npm install and grunt.

**Comment by nuweb** [comment]
I see the problem, there are no files under /vendor/twitter-bootstrap and /src/less/variables.less is trying to refer to @import '../../vendor/twitter-bootstrap/less/variables.less';

**Comment by joshdmiller** [comment]
The readme said to use `--recursive` when you cloned `ng-boilerplate` so that it would get the submodules as well. Looks like you forgot that step! :-)

Try this:

``` sh
$ git submodule init
$ git submodule update
```

**Comment by nuweb** [comment]
Thank you! worked like a charm :+1:
