### ISSUE TITLE
The directory structure for vendor assets should be preserved

### ISSUE THREAD

**Issue by mukgupta** [ngbp/ngbp#170]
I want to use ckeditor in my project . I installed it into vendor directory and included the ckeditor.js file in my project. Now ckeditor.js is copied into build/vendor/ckeditor folder .However , my vendor assets are copied to build/assets folder. ckeditor expects the assets to be present in a fixed location which is something like skins/mono/.. . For it to work the directory structure for assets should also be preserved

**Comment by joshdmiller** [comment]
Projects like ckeditor that have been around a long while have very dated build systems that don't play well with modern tools. This is unfortunate.

However, the solution is quite simple. ckeditor is not meant to be incorporated by build into another project, like one built with ngboilerplate, and so you cannot. Instead, specify the entire `vendor/ckeditor` folder as an asset and it will be copied in its entirety, folder structure preserved. You must then manually reference the root `ckeditor.js` in your `index.html`.

I should note that this is not a good solution; you are copying more files than necessary to your production server and are taking a hit during app load. Unfortunately, any better solution has to come from ckeditor itself and not from ngboilerplate. :-(

Hope this helps! (if not, let me know and I'll reopen)
