### ISSUE TITLE
new js dev getting into AngularJS

### ISSUE THREAD

**Issue by mparisi76** [ngbp/ngbp#171]
Hi, first off, great boilerplate app. Even though I'm still very new to all of these js technologies, I went through the tutorial and it's pretty awesome!

I am originally an actionscript developer turned javascript via backbone/requirejs. I wrote a small backbone app using requireJS and found it to be an extremely powerful library for utilizing modular development/script loading/AMD. Can your boilerplate utilize requireJS or is that a stupid question?

Thanks!

**Comment by 0x6a68** [comment]
there are no stupid question. what you are looking for is: http://docs.angularjs.org/guide/di - so there is no need for AMD in AngularJS, because AngularJS has something similiar, built-in.
