### ISSUE TITLE
Vendor Angular and Bootstrap files?

### ISSUE THREAD

**Issue by iamlesher** [ngbp/ngbp#176]
Where are the vendor/angular and bootstrap directories? I loaded everything up and made no changes, ran grunt watch and it was complaining about the /bootstrap/**.less files not existing. Sure enough, they don't. Is this a missing commit? Is bower not configured properly within this project currently?

**Comment by joshdmiller** [comment]
The `vendor` directory is almost exclusively managed by Bower. In order to get the components installed, you must run `bower install`. The README covers this in the Quick Start and again in more detail in the Detailed Installation section.

**Comment by iamlesher** [comment]
Yeah - that was my point. I ran exactly that and no errors thrown, no vendor directories/files delivered. Strange.

**Comment by joshdmiller** [comment]
What changes have you made to the `bower.json` or `package.json` files? Can you post any changes along with terminal output?

**Comment by iamlesher** [comment]
No changes at all. Pulled the Master, cd'd into the directory, npm install, bower install and this is the output of bower:

bower cached        git://github.com/angular/bower-angular.git#1.0.8
bower validate      1.0.8 against git://github.com/angular/bower-angular.git#~1.0.7
bower cached        git://github.com/angular/bower-angular-mocks.git#1.0.8
bower validate      1.0.8 against git://github.com/angular/bower-angular-mocks.git#~1.0.7
bower cached        git://github.com/twbs/bootstrap.git#2.3.2
bower validate      2.3.2 against git://github.com/twbs/bootstrap.git#~2.3.2
bower cached        git://github.com/angular-ui/bootstrap-bower.git#0.3.0
bower validate      0.3.0 against git://github.com/angular-ui/bootstrap-bower.git#~0.3.0
bower cached        git://github.com/angular-ui/ui-router.git#0.0.1
bower validate      0.0.1 against git://github.com/angular-ui/ui-router.git#~0.0.1
bower cached        git://github.com/angular-ui/ui-utils.git#0.0.4
bower validate      0.0.4 against git://github.com/angular-ui/ui-utils.git#~0.0.3
bower cached        git://github.com/angular/bower-angular.git#1.2.0-rc.2
bower validate      1.2.0-rc.2 against git://github.com/angular/bower-angular.git#>= 1.0.6
bower cached        git://github.com/angular/bower-angular.git#1.2.0-rc.2
bower validate      1.2.0-rc.2 against git://github.com/angular/bower-angular.git#>= 1.0.2
bower cached        git://github.com/components/jquery.git#2.0.3
bower validate      2.0.3 against git://github.com/components/jquery.git#>=1.8.0 <2.1.0
bower install       angular-bootstrap#0.3.0
bower install       angular#1.0.8
bower install       angular-mocks#1.0.8
bower install       angular-ui-router#0.0.1
bower install       angular-ui-utils#0.0.4
bower install       bootstrap#2.3.2
bower install       jquery#2.0.3

angular-bootstrap#0.3.0 bower_components/angular-bootstrap

angular#1.0.8 bower_components/angular

angular-mocks#1.0.8 bower_components/angular-mocks
└── angular#1.0.8

angular-ui-router#0.0.1 bower_components/angular-ui-router
└── angular#1.0.8

angular-ui-utils#0.0.4 bower_components/angular-ui-utils
└── angular#1.0.8

bootstrap#2.3.2 bower_components/bootstrap
└── jquery#2.0.3

jquery#2.0.3 bower_components/jquery

**Comment by joshdmiller** [comment]
It's installing into the `bower_components` directory, but ngBoilerplate uses [`.bowerrc`](https://github.com/ngbp/ng-boilerplate/blob/v0.3.1-release/.bowerrc) to change that to `vendor/`. Did you delete or change that file?

**Comment by iamlesher** [comment]
Yeah, I saw that too. No change to the file at all. Literally just did the above. I figured it would be worth raising up to this project, if perhaps bower changed their management structure or something.

**Comment by joshdmiller** [comment]
Strange... The Bower documentation indicates no such change. What's your
Bower version? `bower --version`

**Comment by iamlesher** [comment]
1.2.7

**Comment by iamlesher** [comment]
Odd - for whatever reason, by .bowerrc file wasn't getting picked up when i cloned the repo. That was the problem. Sorry for the wild goose chase.

**Comment by joshdmiller** [comment]
That's strange indeed. Glad you got it solved though! :-)

**Comment by iamlesher** [comment]
Thanks for your help Josh.
