### ISSUE TITLE
ReferenceError: browser is not defined in /.../xxxx.spec.js

### ISSUE THREAD

**Issue by carywreams** [ngbp/ngbp#177]
attempting to write tests to verify paths exist and are handled by expected controller. The following code is excerpted from the relevant .spec.js file.

```
.
.
.
        describe("Routes", function() {

            beforeEach(function() {
                browser().navigateTo('#/help');
            });

            it('should jump to the /help path when /help is accessed',
                    function() {
                        browser().navigateTo('#/help');
                        expect(browser().location().path()).toBe("/help");
                    });
.
.
.
```

two ReferenceError: ...  messages occur after executing `grunt karma`
The line numbers in the error message correspond to the lines containing the `browser()` usage.

output:

> INFO [karma]: Karma v0.10.2 server started at http://localhost:9018/
> INFO [launcher]: Starting browser Firefox
> WARN [watcher]: Pattern "/home/cary/github_dev/ng-ippt/src/*_/_.coffee" does not match any file.
> INFO [Firefox 24.0.0 (Ubuntu)]: Connected on socket 0ZI5SS3KCJb2XE28-1mr
> .....
> Firefox 24.0.0 (Ubuntu) Module Test ngBoilerplate.help: Routes should jump to the /help path when /help is accessed FAILED
>   ReferenceError: browser is not defined in /home/cary/github_dev/ng-ippt/src/app/help/help.spec.js (line 54)
>   @/home/cary/github_dev/ng-ippt/src/app/help/help.spec.js:54
> 
>   ReferenceError: browser is not defined in /home/cary/github_dev/ng-ippt/src/app/help/help.spec.js (line 59)
>   @/home/cary/github_dev/ng-ippt/src/app/help/help.spec.js:59
> 
> .
> Firefox 24.0.0 (Ubuntu): Executed 7 of 7 (1 FAILED) (0.241 secs / 0.027 secs)
> Warning: Task "karma:continuous" failed. Use --force to continue.
> 
> Aborted due to warnings.

stackoverflow and other resources have suggested making sure the server is running. It looks like that's okay as server has started and is listening on port 9018.

Other suggestions included adding items to the karma configuration, files[] entry:
- JASMINE, JASMINE_ADAPTER 
- ANGULAR_SCENARIO, ANGULAR_SCENARIO_ADAPTER

neither of these changes made any difference in the behavior.

Think I'm missing something fundamental. 

Any suggestions ?

**Comment by joshdmiller** [comment]
The `browser()` calls are part of E2E testing, not unit testing. E2E testing is not part of ngBoilerplate yet, but there is a PR to add it - #67. To make E2E testing work, you have to add `angular-scenario.js` to Karma as well as the Karma scenario runner. Check out that PR for more info.

I'm going to go ahead and close this issue; head on over to #67 and try @rolaveric's implementation. If you encounter further problems, please continue to report them.
