### ISSUE TITLE
Getting stuck at karma:unit:run using grunt watch

### ISSUE THREAD

**Issue by dv336699** [ngbp/ngbp#186]
When the following task runs, grunt gets stuck when using watch.

```
jssrc: {
    files: [ 
      '<%= app_files.js %>'
    ],
    tasks: [ 'jshint:src', 'karma:unit:run', 'copy:build_appjs' ]
  },
```

Here is a video demonstrating the issue:
http://youtu.be/aNI0bAb3cvk (no audio)

Thanks

**Comment by ToucheSir** [comment]
See #37 for a fix :-)
