### ISSUE TITLE
grunt compile does not work

### ISSUE THREAD

**Issue by 16n** [ngbp/ngbp#187]
I think the gruntfile.js has to be improved in the next release cause it is full of little bugs. I fixed nearly all of them (to make a PR) but I can not figure out (I do not have time anymore) a solution for the following problem. If you create the bin folder with grunt compile and point the browser on it it will give you the following error: No module: ngBoilerplate. If you go trough the generated source, you can see that none of the modules and so on is included.

Does anyone know why or even better has a solution for this?

Thanks,
Das Einhorn

**Comment by joshdmiller** [comment]
This is the first I've heard of such a problem. Are you sure you're running `grunt build` before `grunt compile`? Or at least running `grunt` by itself, which will automatically run both?

**Comment by 16n** [comment]
Thanks for the clue... That solved it kind of.
The problem that I have is that the global modules are lost and not global anymore. So if you have like a normal JS file with conf = { foo:bar} that would normally be global, is not not global anymore. Do you have any tipps for that=

**Comment by joshdmiller** [comment]
@daseinhorn Globals are generally frowned upon. Why in your case do you need a global?

FWIW, you can disable this behavior by [commenting out the module prefix and suffix](https://github.com/ngbp/ng-boilerplate/blob/v0.3.1-release/Gruntfile.js#L179) or by changing the contents of `module.suffux` and `module.prefix`, but I don't recommend that course of action.
