### ISSUE TITLE
Shared src folder for multiple projects

### ISSUE THREAD

**Issue by alex6o** [ngbp/ngbp#192]
We are currently developing a website which will consist out of different AngularJS apps that will make use of common services. The main motivation to split the app in multiple apps is the filesize of the js files. Furthermore there are services which are used in all apps, so we have some kind of shared modules. 
Within an individual app the "common"-module approach seams to be very helpful and a great design decision, but how could this approach be extended to a "shared" or multi-app principle?

**Comment by fpirsch** [comment]
Symbolic links ?

**Comment by alex6o** [comment]
hm developer on windows would not be able to build the project or?
another approach could be create for each "module" a git project/branch which are fetched using bower including dependencies (other modules) ... the problem of this concept is the "git" overhead and as far as i know it is not possible to load only "submodules".

**Comment by fpirsch** [comment]
They are available since Windows Vista, with administrator privileges.
Easier than git, which, under windows, is a pain...

**Comment by joshdmiller** [comment]
@mrmuh Good question. In general, there are three solutions: symbolic links, git submodules, and bower packages. Here's a brief overview of my thoughts on all three.

**Symbolic links**: If you're a one-man development team, this works well. As soon as you add additional team members, this becomes a nightmare. Everyone has to organize their directories in the same way and I'm not sure the same symbolic links would work across all platforms. I do not use Windows, so I cannot speak to this.

**Git Submodules**: This is a little bit cleaner from the perspective of multiple teams. I'm not sure what your question was regarding "only submodules" but the project would look something like this:

```
-- src/
  |-- common/
  |   |-- component1 (submodule)
  |   |-- component2 (submodule)
  |   |-- component3 (local)
  |-- app/ (entirely local)
  |-- etc...
```

`component1` and `component2` would be in their own repositories and should be developed independently. You then simply add the submodules to each repository that needs them. 

A similar approach would be to nest all shared code in one logical module and have that be the submodule; e.g.:

```
-- src/
  |-- common/
  |   |-- components (submodule)
  |   |   |-- component1
  |   |   |-- component2
  |   |-- component3 (local)
  |-- app/ (entirely local)
  |-- etc...
```

**Bower**: Long term, this is the best approach. The overhead is smaller, cross-platform support is a little better, and it is consistent with all other shared libraries. In this case, the shared components are considered vendor components and are stored under `vendor/`.

Regardless of which approach, the shared components should be coded and tested _apart_ from the code in which it is used. From my experience, coding the component within one piece and then trying to add it to another, then making further changes to ensure it fits in its new context, and then porting those changes back to the first context, is very, very messy. It is much cleaner to outline needs in advance, create a spec to test for that functionality, and then code it. When the tests pass, add it to your app and it should work out of the box; if it doesn't, there's a problem with your app and not with the shared component. Then, when you need to use it in a different context, you add specs for that case to the shared component, add or change the code, and ensure all tests still pass; then (and only then) does it get integrated into the new context. This is hugely important for avoiding kludges.

Anyway, for my two cents, Bower is the best approach.

**Comment by alex6o** [comment]
thx for the great discussions here and for outlining the pro and cons of the different approaches! at the moment we favor the bower approach too because, as already mentioned, it is the "cleanest" solution for this problem and in addition we can make use of the built in dependency managment.

**Comment by beku8** [comment]
I've just created a new [project](https://github.com/beku8/multi-ngbp) based on ngbp, which has the exact same purpose. 

Bower is a nice approach, but didn't meet my requirement as you can read from my posted issue https://github.com/ngbp/ngbp/issues/291. Hope this helps someone.
