### ISSUE TITLE
Including Angular UI Bootstrap CSS

### ISSUE THREAD

**Issue by mdmoore** [ngbp/ngbp#194]
Just a quick question.  I'm trying to include a Bootstrap accordian by copying the example from the Angular UI demo.  It seems that the accordian css isn't being compiled into the build.  Im not sure what i'm missing.  I created a new route and template which is a copy of the about route and template.  The route is working and the ui is showing up. I've added `ui.bootstrap` as a dependency to my contact module.  

```
angular.module('ngBoilerplate.contact', [
'ui.state',
'placeholders',
'ui.bootstrap'
])
```

I also added `ui.bootstrap` to the ngBoilerplate module in app.js just to be sure.  No luck with either.  Am I missing something?

**Comment by mdmoore** [comment]
Ok so I missed the documentation on using @import in main.less.  That works great.  However, I did notice that there could be some documentation on the individual LESS dependencies for each UI element.  For example, I thought that importing alerts.less would be enough to style the alerts.  But, they also require close.less to style the close button.  It was the same case with the accordian.  I just imported bootstrap.less to cover.

**Comment by davidgorges** [comment]
This issue is more relevant to [Angular-UI Bootstrap](https://github.com/angular-ui/bootstrap)

**Comment by joshdmiller** [comment]
Yeah, this a little bit of a mess, but is really probably more suited to the upstream project (to which I am also a contributor) and may make a good addition to the documentation; of course, to be fair, this is really even more upstream than that with twbs...

Sorry it took so long to reply.
