### ISSUE TITLE
Watch task stops watching JS files after first save

### ISSUE THREAD

**Issue by joshdmiller** [ngbp/ngbp#20]
See karma-runner/grunt-karma#30

**Comment by colthreepv** [comment]
Adding 'delta' to tasks it's a quick work-around... i hope this gets solved on grunt-karma  

``` javascript
src: {
  files: [
    '<%= src.js %>'
  ],
  tasks: [ 'jshint:src', 'karma:unit:run', 'concat:dist', 'ngmin:dist', 'uglify:dist', 'delta' ]
},
```

The process then goes in background (but continues to work!), to kill it you need to do `killall node`
