### ISSUE TITLE
taking "license" out of package.json causes errors in grunt compile

### ISSUE THREAD

**Issue by kenyee** [ngbp/ngbp#205]
You get this error which you can work around by doing "grunt compile --force":

```
Running "concat:compile_js" (concat) task
Warning: An error occurred while processing a template (Cannot read property 'type' of undefined). Use --force to continue.
```

I was modifying the boilerplate for another project when I noticed this while cleaning up the package.json file....customer project doesn't have a license, or bugs, or repository, or homepage url :-)

**Comment by joshdmiller** [comment]
The license and the URL is used in the output of the `app.js`. You can disable that in your project by editing the `meta.banner` in your `Gruntfile.js`.

Let me know if this helps.

**Comment by kenyee** [comment]
Thanks, Josh.  That fixed it :-)
Might be a good idea not to add that license info or maybe add a check that it exists before using it...

**Comment by joshdmiller** [comment]
Glad this solved your problem! 

My perspective is that the license should be included for three reasons: (a) node [recommends it](https://npmjs.org/doc/json.html); (b) we want to encourage open source, wherein a big problem is that too many projects don't specify a license; and (c) even closed-source projects should include a license.

**Comment by kenyee** [comment]
pretty reasonable...I was wondering if closed-source projects should include license links as well (I've never seen one at a company)
It's probably worth documenting via a comment in the package.json that the license is used in Gruntfile.js so others don't hit this if they don't search the issues list :-)
Thanks.
