### ISSUE TITLE
Recess Issue

### ISSUE THREAD

**Issue by ghost** [ngbp/ngbp#206]
Hi,

I have updated the bootstrap ver3.0.3 using bower "bower install bootstrap" it replaced all my less files inside bootstrap once compile my project using grunt it says call and retry 2 allocation failed at "recess:build". Please help me how to proceed further.

Thanks,
Sudarson

**Comment by joshdmiller** [comment]
Did you replace the file references with the new names in `main.less`?

**Comment by ghost** [comment]
Nope...

**Comment by ghost** [comment]
main.less has 
@import '../../vendor/bootstrap/less/mixins.less';
@import '../../vendor/bootstrap/less/grid.less';
@import '../../vendor/bootstrap/less/navs.less';
@import '../../vendor/bootstrap/less/navbar.less';
@import '../../vendor/bootstrap/less/buttons.less';
@import '../../vendor/bootstrap/less/button-groups.less';
@import '../../vendor/bootstrap/less/dropdowns.less';
@import '../../vendor/bootstrap/less/bootstrap.less';
@import '../../vendor/bootstrap/less/pagination.less';
@import '../../vendor/bootstrap/less/responsive-utilities.less';
@import '../../vendor/bootstrap/less/carousel.less';

I also Verified the files in bootstrap/less folder

**Comment by ghost** [comment]
Got it removed all the styles and i added only @import '../../vendor/bootstrap/less/bootstrap.less'; in main.less

**Comment by zba** [comment]
recess not builds newer less files 

https://github.com/twitter/recess/issues/141

is it planned to change this to grunt-task ?
