### ISSUE TITLE
gulp in place of grunt hacks

### ISSUE THREAD

**Issue by pajooh** [ngbp/ngbp#211]
just updated my mind to gulp :)

**Comment by fraserxu** [comment]
vote for gulp!

**Comment by dv336699** [comment]
+1 for gulp
http://www.100percentjs.com/just-like-grunt-gulp-browserify-now/

**Comment by 0x6a68** [comment]
generally i think this could enhance the whole workflow. but before rewriting the build-process, i also think that several parts should be refactor. i have ported major parts already to gulp, just for learning and testing. the result was that it increases the whole workflow performance, from around 1.5s to 0.3s. 

So if this project is going to switch from grunt to gulp, i will help, but primarily i think it should start from scratch and please rethink if some parts could be done better or removed.

**Comment by joshdmiller** [comment]
The next version of ngbp will use a completely "from-scratch" build system called Warlock. It is inspired in some ways by Gulp (it uses streams, so performance is fantastic - the `build` task takes <100ms) but is very, very different - and magical! I'm looking for alpha testers (and of course contributors) so if you're interested in helping out, [let's get to work](http://getwarlock.com).

The current `v0.3` branch will continue to get maintenance updates and bug fixes, but will stick with Grunt, so I'm going to close this issue.
