### ISSUE TITLE
Can't get Karma to run properly (Fatal error: socket hang up)

### ISSUE THREAD

**Issue by dillonforrest** [ngbp/ngbp#226]
I describe the problem in https://github.com/karma-runner/grunt-karma/issues/92, since my hunch is that this is more a `grunt-karma` problem and less a `ng-boilerplate` problem.... but my hunch is that my hunch could be wildly misinformed.  ~____~

Would anybody happen to know why I can't get Karma working with my project based on `ng-boilerplate`?  o__O

**Comment by Merott** [comment]
There has been a few references to this problem. See #153 for the solution.

**Comment by dillonforrest** [comment]
Works perfectly.  Thanks @Merott!!  :)
