### ISSUE TITLE
Bootstrap CSS issues

### ISSUE THREAD

**Issue by kuzmak** [ngbp/ngbp#237]
Could someone please give me a suggestion on how the following issue can be resolved? I've installed ngbp using provided instructions and everything seems to work fine. Then I tried adding a simple bootstrap-styled table to the app/home/home.tpl.html file:

``` html
  <table class="table table-striped">
      <tr>
          <td>Row 1, Cell 1</td>
      </tr>
      <tr>
          <td>Row 2, Cell 1</td>
          <td>Row 2, Cell 2</td>
      </tr>
      <tr>
          <td>Row 3, Cell 1</td>
      </tr>
  </table>
```

But the table doesn't render correctly on reload:
![selection_158](https://f.cloud.github.com/assets/656316/2456980/7bf72cfc-af29-11e3-9d2a-24defac2ea18.png)

If I replace the content of build/assets/ng-boilerplate-0.3.1.css with standard bootstrap.css file (copied from https://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css), the table renders correctly:

![selection_160](https://f.cloud.github.com/assets/656316/2456991/bafc2718-af29-11e3-9209-1b2caa0affc8.png)

**Comment by vrodriguezTecsisa** [comment]
You should go to main.less file and import the tables-bootstrap-less file:

@import '../../vendor/bootstrap/less/tables.less';

Or easier, you can just import all the bootstrap styles:

@import '../../vendor/bootstrap/less/bootstrap.less';

Hope it helps

**Comment by kuzmak** [comment]
Thank you, that resolved my issue!
