### ISSUE TITLE
use ng-annotate instead of ngmin

### ISSUE THREAD

**Issue by capaj** [ngbp/ngbp#251]
You should switch your annotation plugin https://github.com/olov/ng-annotate, it is way way faster and reliable. It is not a big problem for smaller apps, but as your code gets bigger, it becames bigger and bigger pain.

**Comment by 27leaves** [comment]
+1

**Comment by joshdmiller** [comment]
v0.4 uses `ng-annotate`. If you want to become an enterprising alpha tester, visit http://getwarlock.com. Since the work is already done for that release, I'll go ahead and close this because I have no intention of making such a major change just for a patch release, but I would gladly accept a PR.
