### ISSUE TITLE
e2e testing

### ISSUE THREAD

**Issue by ErichBSchulz** [ngbp/ngbp#259]
the angular-seed project (which is not nearly as awesome as ngbp) included e2e testing

https://github.com/angular/angular-seed#end-to-end-testing

as a complete newb - I'm curious why ngbp doesn't include it? do you think unit tests are adequate - or is there another approach?

**Comment by joshdmiller** [comment]
> do you think unit tests are adequate - or is there another approach?

Absolutely not. E2E testing is a must. It just hasn't been done yet. 

That said, the current Grunt-based build system will be moving to maintenance mode with the `v0.4` in favor of a [newer one](http://getwarlock.com) (same ngbp, but better), so I doubt this will get done in the `v0.3` branch unless someone submits a solid pull request. The new build system will have E2E support in the form of Protractor, just like `angular-seed`. The new version (_without_ e2e) is available for alpha testing right now, but I can confirm neither when a stable version will be released nor when the alpha will have E2E support, but it should be very soon - we've got some wonderful contributors working hard to make it awesome. :-)

There are a couple of existing issues to add E2E support (e.g. #39, #196), so I'm going to close this as a duplicate, but definitely feel free to keep the discussion going if you have questions.
