### ISSUE TITLE
Project Directory size after Grunting

### ISSUE THREAD

**Issue by kenblood** [ngbp/ngbp#263]
Trying to get up to speed on AngularJS.  Very little experience with web devp, and none with Angular, but many years, environments, and languages behind me. After reading a lot, decided to re-implement one of my old Asp.Net apps as a way to learn Angular, etc.   Selected ngbp as a rational approach to project organization.   I downloaded the ngbp files from github (100KB, 35 files, 11 directories), and made a copy of the ngbp root & subs for the project.  

Then I Grunted it.   Already had Grunt installed globally, but followed the directions to install Grunt in the project (>cd project-root and >grunt install).   Now that it's all done, my project directory is 68.1 MB, 9293 files, 2006 directories!    Most of that is in the node_modules directory.

Does that sound normal or did something go wrong?   I realize that very little of that stuff would get deployed, but even as a DEV project directory that seems extreme.  

If that seems extreme, I'll start over & be more careful.   If that seems normal, I think the Grunt way might not be my way.   There has to be a better approach.   I'm aware of Gulp.js, Mimosa, Brunch.io.  There may be others.    

I believe that ngbp IS a rational starting point.  I just want to avoid such a heavy load of per-project stuff as Grunt seems to need.

Any advice?

**Comment by joshdmiller** [comment]
This is a common concern. Right away, let's distinguish between the deployable size of your application and the size of the tools used to build it. ngbp ensures the latter is very small; just check out the size of the `bin/` folder. Not one thing from `node_modules/` and very little from `vendor/` will be there.

As for the tools, this is almost completely beyond our control. Grunt, Gulp, and a new build system called [Warlock](http://getwarlock.com) for the next version of ngbp all run on Node and as such use npm to manage dependencies. Grunt, Gulp, and Warlock each have their own dependencies, which are relatively small. But the tasks the build system _uses_ each have their own dependencies, and these dependencies have dependencies, and it adds up quickly. What you're seeing is not unusual, but everyone usually has the same reaction you did; I know I did.

Warlock will actually help with this _a little_ by only installing the features you actually use. E.g., if there's no CoffeeScript in your app, you shouldn't need the dependencies. But it won't be a panacea. This is the state of things and it's largely unavoidable.

So the "problem" - assuming that's even the correct classification - isn't with Grunt, but the underlying ecosystem that powers it - and there are no serious alternatives.

**Comment by kenblood** [comment]
Josh, Thanks for your careful and thorough explanation of the issues.   I guess I should remember that these are still the "Wild West" days of full-on browser based apps, and not worry about the minor stuff.  I'm glad that pioneers like yourself are on the ground moving things forward!

**Comment by joshdmiller** [comment]
@kenblood You're welcome. :-)
