### ISSUE TITLE
Question: Does ng-boilerplate build system work with this project structure out of the box

### ISSUE THREAD

**Issue by bastienJS** [ngbp/ngbp#264]
I have a modular project structure and I would like to make some little changes to your template that it rather looks like this:

![modularization](https://cloud.githubusercontent.com/assets/5945955/3052049/e079451e-e194-11e3-8181-1ab9694e9584.PNG)

Forget about the separate test folder I could also put a file 'BrowseSchoolyearsController/Service/etc.../Test.js'

 next to each application item.

Does your build system work with this structure or would I have to completely rewrite it? All the grunt stuff...

**Comment by joshdmiller** [comment]
I don't know. ngbp aims to be very flexible, but it does focus on best practices and I don't recommend the directory structure you're outlined. One of the key philosophies of ngbp is that components be drag-and-drop reusable, which your structure does not accomplish.

Take a look at the globbing patterns in the `build.config.js` file. If changing those patterns will result in the correct files being read, then absolutely - ngbp will work swimmingly. If not, there may need to be changes to the Gruntfile to accommodate your structure.
