### ISSUE TITLE
bootstrap scrollspy

### ISSUE THREAD

**Issue by robotnic** [ngbp/ngbp#272]
I want to make a sidenavigation like here on the right side:
http://getbootstrap.com/components/

The navigation uses anchors und ui-router is using anchors. It does not fit together. How to solve this problem?

**Comment by joshdmiller** [comment]
I'm not sure I follow what your specific issue is - or how it relates to ngbp. Can you say a little more about what you're trying to accomplish and why it doesn't work with ngbp?

**Comment by robotnic** [comment]
It does not really relate to ngbp. The problem is in the combination of ui.router and ui.bootstrap.
I solved this problem using angular-strap.

http://mgcrea.github.io/angular-strap/##scrollspy
