### ISSUE TITLE
Nested state doesn't work

### ISSUE THREAD

**Issue by ghost** [ngbp/ngbp#282]
Hello, I have the following problem. When I'm trying to access `/#/survey` it works and shows `survey.tpl.html`, but when I'm trying to access `/#/survey/start/235` it still shows `survey.tpl.html` instead of `survey.start.tpl.html`.

``` javascript
angular.module( 'ngBoilerplate.survey', [
'ui.router',
'placeholders',
'ui.bootstrap'
])

.config(function config( $stateProvider ) {
    $stateProvider
    .state( 'survey', {
        url: '/survey',
        data:{ pageTitle: 'Just survey page' },
        views: {
            "main": {
                controller: function($scope, $stateParams){
                    console.log('just survey lala', $stateParams);
                },
                templateUrl: 'survey/survey.tpl.html'
            }
        }
    })
    .state( 'survey.start', {
        url: '/start/:id',
        data:{ pageTitle: 'Start this fukken survey'},
        views: {
            "main": {
                controller: function($scope, $stateParams){
                    console.log($stateParams.id);
                    console.log('i got id');
                },
                templateUrl: 'survey/survey.start.tpl.html'
            }
        }

    });



})
;
```

**Comment by ghost** [comment]
Also I've been trying to avoid using `views` as mentioned in [ui-router documentation](https://github.com/angular-ui/ui-router/wiki/URL-Routing#important-stateparams-gotcha), but routes stopped working at all.

**Comment by joshdmiller** [comment]
This may be just a typo on the issue filing, but you don't seem to have a
route defined matching `/survey/start/123`.

As for the second bit, I'm not sure what the issue is; can you elaborate?

**Comment by ghost** [comment]
Josh, thank you for your answer. I am passing `123` as a value of `id` parameter via `<a href ui-sref="survey.start({id: 235})">Link</a>` and this construction generates `http://hostname/#/survey/start/123`, so I'm trying to catch this value with `:id`.

**Comment by anho** [comment]
How does your `survey/survey.tpl.html` look like? But for me this does not look like a problem related to ngbp.

**Comment by ghost** [comment]
It contains nothing but text.

**Comment by anho** [comment]
Most likely, that is the problem. You need to tell Angular where to put the nested view. So the parent template needs to have the `ui-view` directive somewhere. More on that can be found [here](https://github.com/angular-ui/ui-router/wiki/Nested-States-%26-Nested-Views#nested-states--views).

**Comment by ghost** [comment]
Thank you anho, your answer was really helpful. I'm sorry for the inconvenience, this issue is related to my documentation reading skills and has nothing to do with ngbp.
