### ISSUE TITLE
Added folder under src/app/ with needed files, and no results...

### ISSUE THREAD

**Issue by ladaltamirano** [ngbp/ngbp#286]
Ok, I've added a folder under src/app/ with the needed files, and a section in the header to access this route, but the route is not mapped. When a click on the new navbar item I get " Error: Could not resolve 'newpage' from state '' "..., what is it lacking? I think I've tried almost everything...
Added files:
newpage/newpage.js
newpage/newpage.tpl.html
Shouldn't these be added automatically by line 23 in build.config.js? Why is it no appearing in the built index.html version?

**Comment by Kevin-A** [comment]
Have you tried stopping `grunt watch` and then start `grunt watch` again?

**Comment by ladaltamirano** [comment]
Yeah, I've already tried it, but still the same error: Error: Could not resolve 'newpage' from state ''

**Comment by joshdmiller** [comment]
It will be **very** hard to diagnose without seeing the code. This could be a build problem or UI router problem or some other problem. The only thing I can think to ask without seeing code is to make sure you required the `newpage` module in your `app` module.

**Comment by ladaltamirano** [comment]
Oooohhhh... F#$%k! Why in the #$% I didn't see that!... Ok..., maybe it was too late at night, right? Thank you Josh (Y) !

**Comment by joshdmiller** [comment]
I win!

Actually, I only guessed that because I've done it more times than I'd care to admit. I almost created a module as part of the build to auto-include these, but that would break a lot of the code reusability and (I think) decrease readability a bit. Being explicit about module structure is probably a good thing.

If that doesn't solve it, we'll reopen this.

**Comment by ladaltamirano** [comment]
I think it's great as it is. My bad for trying to code at the edge of the night. Now fresh to go!...
