### ISSUE TITLE
Custom bootstrap theme

### ISSUE THREAD

**Issue by Kevin-A** [ngbp/ngbp#287]
I've bought a theme from wrapbootstrap.com (INSPINIA) and I'm having trouble implementing it (in a proper way). I tried replacing `/vendor/bootstrap/dist/*.css` files, the theme unfortunately doesn't have LESS files yet so I couldn't replace the ones in `/vendor/bootstrap/less`. 

I have also added the following to `vendor_files`, but it fails hacky:

``` javascript
vendor_files: {
      js: [
        'vendor/inspinia/js/jquery-1.10.2.js',
        'vendor/inspinia/js/inspinia.js',
        'vendor/inspinia/js/jquery-ui.custom.min.js',
        'vendor/inspinia/js/jquiry-ui-1.10.4.min.js',
        'vendor/inspinia/js/plugins/metisMenu/jquery.metisMenu.js',
        'vendor/inspinia/js/plugins/pace/pace.min.js'
      ],
      css: [
        'vendor/inspinia/css/style.css',
        'vendor/inspinia/css/animate.css'
      ],
      assets: [...]
  },
```

There are multiple issues:
1. It doesn't work well, unless I add a bunch (10+) files to `vendor_files`
2. It depends on jQuery, which means I'll have to include it. UI-bootstrap is partly about removing that dependency
3. It's somewhat difficult and error prone (too many imports, wrong version matches and what not)

I'm quite sure someone has done this before, how would one go about doing this?

**Comment by ghost** [comment]
Hey @Kevin-A  , did you manage to fix this, also bought inspinia and would like to integrate them together
