### ISSUE TITLE
The command mentioned in installation docs is incorrect. 

### ISSUE THREAD

**Issue by LoveleenS** [ngbp/ngbp#289]
The cloning command mentioned in README doc is 
git clone git://github.com/joshdmiller/ng-boilerplate my-project
The correct command should have http or https as shown below:  
git clone http://github.com/joshdmiller/ng-boilerplate my-project

**Comment by jeroennoten** [comment]
`git clone git://github.com/joshdmiller/ng-boilerplate my-project` does work for me...

``` sh
git clone git://github.com/joshdmiller/ng-boilerplate
Cloning into 'ng-boilerplate'...
remote: Counting objects: 707, done.
remote: Total 707 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (707/707), 848.59 KiB | 273.00 KiB/s, done.
Resolving deltas: 100% (293/293), done.
Checking connectivity... done.
```

**Comment by joshdmiller** [comment]
Yes, this command is correct, though the `https` version will work as well - as will the `git@` version. There are several variations. Considering those _using_ ngbp are not going to be pushing back to `ngbp/ngbp`, the `git://` version is fine. But use whichever you choose. :-)
