### ISSUE TITLE
Cloud9

### ISSUE THREAD

**Issue by randallmeeker** [ngbp/ngbp#290]
Anyone used this with Cloud9's IDE? I'm hacking through it now and wondered if someone already had a config out there.

**Comment by A-Zak** [comment]
I just tried it, and the only thing that wasn't working for me is the karma integration (because it tried to run firefox)... All you need to do is to replace the firefox launcher with [PhantomJS Launcher](https://github.com/karma-runner/karma-phantomjs-launcher) and you're good to go... :)

**Comment by randallmeeker** [comment]
Ya, phantom did the trick, works great.

**Comment by A-Zak** [comment]
glad I could help :)
