### ISSUE TITLE
Which is the right way of crediting @joshdmiller's ngbp in our own projects?

### ISSUE THREAD

**Issue by albertboada** [ngbp/ngbp#292]
Hey guys, just a silly question...

When using `ngbp` for kickstarting our projects, which would be the right way of specifying our own license, owning the project, etc. in our repository, but still crediting (and respecting) the original license and its author (@joshdmiller)? _e.g._ How should we leave `/package.json` and `/LICENSE` files?

**Comment by joshdmiller** [comment]
Thanks for asking! :-)

ngbp is released under the MIT license and, most likely, `Gruntfile.js` is the only thing in a real project that is even recognizable as originating from ngbp; the file structure and whatnot are not subject to the license. A note in a comment at the top of the gruntfile would more than sufficient as far as I am concerned:

``` js
/**
 * Build script based on ngbp. https://github.com/ngbp/ngbp
 */
```

Of course, feel free to credit ngbp in any way you wish, such as in a README file or something. I'm not worried too about it.

Definitely change your `package.json` to suit your project's needs - including the author and copyright. Also ensure your project has a `LICENSE` file suitable for your work, whether open or proprietary.

**Comment by albertboada** [comment]
Fantastic, will do as you say! `Gruntfile` and `README` make sense the most to me, too.

Thanks a lot for answering and even more for the hard work! `ngbp` does help A LOT! :)
