### ISSUE TITLE
Newb question about karma-unit.tpl.js

### ISSUE THREAD

**Issue by alltg** [ngbp/ngbp#294]
I'm new to angular.  Thanks very much for ngbp.  It's so great!

I'm really new to testing and karma and have a couple questions about karma-unit.tpl.js in ngbp:

It's identical to what others might call karma.conf.js, correct?  If so, why not call it karma.conf.js?

Also, because it has the tpl in its name, I, at first, assumed that it might be treated as a master template and that app-related changes or additions might ultimately be made to another file, potentially karma-unit.js (which I would need to create - the docs also reference a karma-unit.js, which kind of got me thinking in this direction, but it wasn't included in my karma directory...)  If I create a karma-unit.js, would those changes be incorporated into the built file?  Am I on the right track here, or not at all?

thanks so much :)
-Clueless on testing

EDIT:   Here's some context for my question too:

I installed the angular-google-maps library and had some trouble figuring out how to implement the correct load order of the scripts (since the google api has to be available before angular) - see this thread: https://github.com/angular-ui/angular-google-maps/issues/270

Hardcoding the URL in the karma-unit.tpl.js seemed weird to me (but maybe it shouldn't?)  It got me wondering if I could include a separate files = []; in a karma-unit.js file that would be included in the build along with the tpl file (although I would probably still run into a load-order-issue in this case as well.)

```
    files: [
      'http://maps.googleapis.com/maps/api/js?sensor=false&language=en', <% scripts.forEach(function(file) { %> '<%= file %>', <%
      }); %>
      'src/**/*.js'
    ],
```

It also seems that build.config.js won't include any absolute path with http:// in it when including vendor_files, so when including this google api for the main site, I have to include it in script tags in index.html instead of in the vendor_files array - just like the plusone example you have.  Why is that?  Sorry if this is an old question - either I'm terrible at googling or I'm not looking for the correct stuff.  Thanks so much.:)

**Comment by joshdmiller** [comment]
Hello!

That file _is_ a template, but it's handled by the build script. After you run the build, you'll find the compiled version in `build/`. The script files handled by the build are automatically included and should not be added manually. The files are added in the same order they are found in the `vendor` arrays in `build.config.js`.

As for CDN libraries, those need to be added manually to the `index.html` because they are not intended to be _processed_ by the build.

Let me know if this doesn't resolve it.

**Comment by alltg** [comment]
Thanks Josh.  That makes sense and reminds me to think of this more as a build-system and less as individual parts - which helps my particular way of thinking.  I just need to spend more time with it too.  Thanks for the quick response.  I really appreciate it.

**Comment by joshdmiller** [comment]
You're welcome! Client-side build tools are a bit of a mess at this point due to a variety of factors, something [I hope to help correct soon](http://docs.getwarlock.com).

I'll go ahead and close this, but feel free to follow up if you have more questions.

**Comment by douglascorrea** [comment]
Hi @joshdmiller I also had the same question and actually the karma config is not being generated to me, and I saw that build.config.js is not threating karma directory. Can you please tell me how can did you planned to compile that file in ng-Boilerplate?

**Comment by douglascorrea** [comment]
Sorry @joshdmiller just found what is wrong. Thank you anyway :)
