### ISSUE TITLE
change the name 'ng app="ng-boilerplate", how?

### ISSUE THREAD

**Issue by cliffmattern** [ngbp/ngbp#302]
How is it possible to change the name 'ng app="ng-boilerplate"'? Where anywhere?

**Comment by PaulL1** [comment]
You change in a handful of places:
1.  In app.js, you need to change the module name
2.  In index.html you need to change ng-app=
3.  Tidier to change it in places like package.json

This segment of my tutorial deals with some of the tidyup from the ngbp sample to a personalised app: http://technpol.wordpress.com/2013/11/16/4-adding-a-basic-list-using-resource-for-a-restful-query-from-rails/

**Comment by cliffmattern** [comment]
Thank you very much for the reply and your tutorial.

I'll make the changes. I thought something like that for me.
