### ISSUE TITLE
Ajax in ngbp? -question

### ISSUE THREAD

**Issue by tranloi** [ngbp/ngbp#314]
Hi,
I used Kendo-UI and call ajax.But I got the error the file not found.Can you have any advices foe me.Please take a look the attachment.

![ngbp](https://cloud.githubusercontent.com/assets/7908389/4198729/e6beedfc-37fc-11e4-957c-03a710890c8e.png)

Thanks,
Loi

**Comment by benjaminsuch** [comment]
This has absolutely nothing to do with the purpose of ng-boilerplate, I'm sorry. All templates are cached  in the $templateCache service.
