### ISSUE TITLE
Adding templates does not execut grunt copy

### ISSUE THREAD

**Issue by benjaminsuch** [ngbp/ngbp#315]
Hello,

When I add a template to my module folder, grunt does not rerun the copy task. This is pretty annoying because everytime when I add an .html file into my folders I have to end the "grunt watch" task and rerun it.

Am I doing something wrong? I haven't changed anything on the config files, just removed the default app files from ngbp.

Edit: nvm. it does add the templates to the build folder, I just didn't look on the right place ^^.

**Comment by PaulL1** [comment]
My understanding is that grunt watch isn't capable of noticing new files, only changes to old files.  I think this is a known problem that comes from the upstream tool.
