### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by Tallyb** [ngbp/ngbp#326]
please add a favicon support (index.html, grunt copy).

**Comment by vijay-joshi** [comment]
Link to favicon in index.html and keep the favicon file in assets/images. It will automatically get copied.

**Comment by joshdmiller** [comment]
If someone wants to add an ngbp favicon and submit a PR, I'll happily merge it. Until then, it is simple to implement per-project (as mentioned above), so I'm going to close this issue for now.
