### ISSUE TITLE
how to run application via Grunt on localhost ?

### ISSUE THREAD

**Issue by akhilclarion** [ngbp/ngbp#353]
hi 

I am new to this, please help me, how can run to application via Grunt on localhost ?

**Comment by saibotsivad** [comment]
Grunt is a task runner, so what it does is runs tasks like: concatenate all JavaScript files into one file. Grunt isn't really meant to act as a server (although there are Grunt plugins that can do that).

I just added a [page to the wiki](https://github.com/ngbp/ngbp/wiki/Simple-file-server) describing a really simple server that comes pre-installed on most computers. See if that helps you.

**Comment by akhilclarion** [comment]
Thanks you so much.....
