### ISSUE TITLE
 ReferenceError: angular is not defined

### ISSUE THREAD

**Issue by roylee0704** [ngbp/ngbp#361]
This happens to me when I was trying to use cdn version of `AngularJs` as rather than bower install `angular.js` itself. 

To be specific, the error stated on the topic will be shown whenever I hit `grunt` or `grunt watch`.

**Comment by roylee0704** [comment]
Okay, I have figured out the problem, you need to include the cdn version of `AngularJs` to **karma-unit.tpl.js**, so that karma could resolve the file during testing.

``` js
    /**
     * This is the list of file patterns to load into the browser during testing.
     */
    files: [
        'https://ajax.googleapis.com/ajax/libs/angularjs/1.2.27/angular.min.js',
        <% scripts.forEach( function ( file ) { %>'<%= file %>',
      <% }); %>
      'src/**/*.js',
      'src/**/*.coffee',
    ],

```

**Comment by joshdmiller** [comment]
Yes, it will need to be included in karma manually in that case, though I'd like this to be more flexible in the future.

I'm glad you got this solved!
