### ISSUE TITLE
grunt concat module.prefix and module.suffix

### ISSUE THREAD

**Issue by sabrehagen** [ngbp/ngbp#381]
In your concat task in your grunfile you specify `module.prefix` and `module.suffix` in the source for the compile_js task. I've search the grunt concat repo and can't find any references to module.prefix nor module.suffix. What do they do?

**Comment by joshdmiller** [comment]
[`module.prefix`](https://github.com/ngbp/ngbp/blob/v0.3.2-release/module.prefix) and [`module.suffix`](https://github.com/ngbp/ngbp/blob/v0.3.2-release/module.suffix) are **files** in the repository that we use to wrap our code in an IIFE (immediately-invoked function expression). They are simply prepended and appended, respectively, to the generated code file.

You've overthought it! :smile:

**Comment by sabrehagen** [comment]
I didn't expect that :) Why is the third argument of module.prefix undefined?

**Comment by joshdmiller** [comment]
Good question! Two reasons: it helps code minify by saving bytes on commonly-used variables and it helps ensure some other library can't overwrite the definition of `undefined` with something else globally and still affect your code. E.g. `undefined = true` is both possible and disastrous.
