### ISSUE TITLE
Images in build path

### ISSUE THREAD

**Issue by ervbsankar** [ngbp/ngbp#383]
do i have to create a new entry in Vendor_files: in build.config.js.

I am using custom images to show on the screens. Please help me on this

**Comment by Merott** [comment]
Use [`vendor_files.assets`](https://github.com/ngbp/ngbp/blob/v0.3.2-release/build.config.js#L73), they're copied unprocessed.

**Comment by ervbsankar** [comment]
Thank you. i have put my images in src/assets
