### ISSUE TITLE
Please describe how to properly deploy ngbp to production.

### ISSUE THREAD

**Issue by noisy** [ngbp/ngbp#388]
Maybe I am just doing it wrong but when I want to serve my code with nginx, I got this same error, like when I simply open a compiled sources:

```
git clone https://github.com/ngbp/ngbp.git
cd ngbp/
npm install
bower install
grunt compile
google-chrome bin/index.html
```

How exactly ngbp should be deployed?

**Comment by noisy** [comment]
I also asked a question about my problem on StackOverflow: http://stackoverflow.com/questions/30624489/how-to-properly-deploy-angular-application-based-on-ngboilerplate-and-using-ngi

**Comment by joshdmiller** [comment]
Sorry you're having trouble. I've responded to the SO post, so we can take the conversation there.
