### ISSUE TITLE
Documentation about variables in views

### ISSUE THREAD

**Issue by julkue** [ngbp/ngbp#391]
After reviewing the builded project I saw that there were a few variables replaced with some values in index.html, e.g. `<%= version %>`. Is there any documentation about the variables that can be used and which values they will take on?

Thank you!

**Comment by joshdmiller** [comment]
Unfortunately, there is no formal documentation for those variables, but you can see [here](https://github.com/ngbp/ngbp/blob/v0.3.2-release/Gruntfile.js#L621) that we only include the three used variables. However, any values you add to this object will be available for use in the template.

Is there something specific you're wanting to do in the template that I can help with?

**Comment by julkue** [comment]
Thanks for the hint. I loved that you don't need to put in the version manually. So I thought all defined options in the JSON will be a variable and tried using the "name"-option but of course it didn't work.

I try creating a template that I can use in each of my projects. So it would be cool to have the ability to access _all properties_ of the JSON, not just the version.

However, since I know this is not possible for now I can live with it. However, if there is someone who thinks this is only a small implementation I would appreciate if the one would implement it.

**Comment by joshdmiller** [comment]
If you're referring to the `package.json`, you could just do this:

``` js
return grunt.template.process( contents, {
  data: {
    scripts: jsFiles,
    styles: cssFiles,
    version: grunt.config( 'pkg.version' ),
    json: taskConfig.pkg
  }
});
```

And the use it like so: `<%= json.name %>`.
