### ISSUE TITLE
I am working on this from windows 10

### ISSUE THREAD

**Issue by winnemucca** [ngbp/ngbp#401]
I have grunt watch open.  Grunt watch is working fine.   However, when I paste in file:///path/to/ng-boilerplate/build/index.html.  I am not able to get into the app.  I am getting this webpage is not found.  I downloaded live reload from the chrome store.  Also, I tried running this on a http-server.  I followed the src folder but was not able to find my content.

**Comment by joshdmiller** [comment]
Do you mean you _literally_ pasted in that path? It's supposed to be the path on your file system where it is stored. If you're on Windows, it might be something like `file:///C:/wherever/ngbp/is/build/index.html`. You can probably just double-click it from your file explorer too.

**Comment by winnemucca** [comment]
no not literally.  Sorry for not being clear.

**Comment by joshdmiller** [comment]
Oh, phew. lol. Okay, next step - can you post the contents of the `build/` dir and the output of grunt?

**Comment by winnemucca** [comment]
I uninstalled everything and started over.  I did my bower install and I
checked my path again to be sure. I installed some text changes.  Nothing
changed.  I see that I do not have my stylesheets loading but I can figure
that out.  Not sure the error, but I will this should be me navigating
through.  I apologize for the ticket.

**Comment by joshdmiller** [comment]
Not a problem. Let me know if you have more trouble!
