### ISSUE TITLE
recess:build broken ">> TypeError: Cannot call method 'map' of undefined"

### ISSUE THREAD

**Issue by shanestillwell** [ngbp/ngbp#42]
```
Shanes-MacBook-Air:less shane$ grunt recess:build
Running "recess:build" (recess) task
>> TypeError: Cannot call method 'map' of undefined
Warning:  Use --force to continue.

Aborted due to warnings.  
```

Related to mainstream bug, keep updated on respective mainstream issues:

twitter/bootstrap#8088
twitter/recess#96  

In a nutshell... recess installs `less` 1.4.0 (beta) instead of 1.3.3

**Comment by prdonahue** [comment]
How can we temporarily (and locally) modify recess so that it installs 1.3.3?

**Comment by mdunham** [comment]
npm uninstall less@beta

npm install less@1.3.3

or add -g if your using globals

**Comment by raejin** [comment]
@mdunham I tried, but I think this wouldn't solve the problem as it appears to be extraneous a package.

**Comment by MatejBalantic** [comment]
I fixed mine by going into folder
node_modules/grunt-recess/node_modules/recess/

than opening package.json and changing
"less": ">= 1.3.0" 
to
"less": "~ 1.3.0" 

than running
npm update

**Comment by colthreepv** [comment]
on my personal project (that uses this boilerplate), i fixed it using a Makefile rule...

you can check it [on this commit](https://github.com/mrgamer/musicpad/commit/132a1ad0c99da2983b6f2dd811c208c5b73e6d30)

**Comment by raejin** [comment]
@skavt Thanks that solves it!

**Comment by joshdmiller** [comment]
It looks like this has been solved upstream, so I'll go ahead and close this issue. Let me know if I need to reopen it.
