### ISSUE TITLE
Can't seem to keep auto build/load going for more than 10 or so minutes

### ISSUE THREAD

**Issue by willmruzek** [ngbp/ngbp#44]
I'm running 'grunt watch' using mingw on Windows. The page stops reloading (via LiveReload) after the script reaches:
'Running "uglify:dist" (uglify task)
File " dist/assets/app-name.min.js" created
Done, without errors.'

This has happened multiple times while trying to add a new module to ng-boilerplate.

**Comment by joshdmiller** [comment]
Hmmm. I'm don't run Windows, so I can't really test...or provide any help at all, really. :-/ But I'll try!

Okay, when you say "add a new module" do you mean creating a new file?

Is anyone else having this issue?

**Comment by willmruzek** [comment]
Say when I'm working on adding a 'watch' module with its own controller, templates, and assets. It would handle displaying a video from YouTube or Vimeo.

While developing, the LiveReload only works until the above messages.

Since it's basically running on a emulated unix command line, I doubt the OS is the problem.

**Comment by joshdmiller** [comment]
There hasn't been any activity on this issue for a few months, so I'll go ahead and close it. If anyone is still having this problem, I'm happy to reopen it.
