### ISSUE TITLE
 Karma Tests don't use build output location

### ISSUE THREAD

**Issue by nikolawannabe** [ngbp/ngbp#47]
The karma-unit.js file has the build output location hard-coded to the dist folder on [Line 15](https://github.com/joshdmiller/ng-boilerplate/blob/master/karma/karma-unit.js#L15).

This causes the following error with grunt watch:

```
WARN [watcher]: Pattern "/home/me/src/js/dist/tmp/**/*.js" does not match any file.
```

It would be better if this could come from the build output location variable.

**Comment by joshdmiller** [comment]
Hey @nikolawannabe! Indeed that'll do it. I fixed this but it's not on `master` yet: 3384b6f. Take a look and let me know what you think. It'll get merged in the next day or so but I need to finish some docs.

(PS: I'm closing this even though it's not on the master branch just to get it off my to do list)
