### ISSUE TITLE
Add CoffeeScript support

### ISSUE THREAD

**Issue by mgibowski** [ngbp/ngbp#48]
Hey Josh,

I like your kickstarter and as I code in CoffeeScript, I created this fork:
https://github.com/mgibowski/ng-boilerplate

Let me know if you'd like me to do a pull request. It adds coffee script support but does not do any harm if you don't have coffee scripts in your project.

The only intrusive thing I did was migrating the app.js and app.spec.js into coffeescript. I can remove these changes before creating a PR.

And thanx for your great effort, this boilerplate is really cool!

**Comment by joshdmiller** [comment]
That's a great suggestion. For v0.3, which is a work in progress, I pretty heavily modified the Gruntfile so your changes would be difficult to merge. The good news is that the new format makes it _much_ easier to incorporate CoffeeScript. So I did it! It's not on `master` yet, but check it out: 17957233e16bf902d0eca9f46fbbc476291a53ff. It includes linting too. Let me know what you think.

**Comment by mgibowski** [comment]
Oh, great to hear that! I think I will stay with my fork for now and as soon as v0.3 will be there I will switch to it.

**Comment by joshdmiller** [comment]
0f308f2f676897073ffb1d02d1ccc29ca3409d92 is now in master. w00t! Thanks, @mgibowski!
