### ISSUE TITLE
Attempting to use angular-resource but keep geting "Error: No module: ngResource"

### ISSUE THREAD

**Issue by grantlucas** [ngbp/ngbp#52]
Ok. Have bashed my head a bit trying to get this working last night but have been unsuccessful. I want to use ngResource in my app but something isn't working.

I previously had ngResource working with the angular seed app but in the port over to ngBoilerplate, I'm missing something.

**NB:** I'm fairly new to AngularJS, GruntJS etc so it's highly possible I'm just missing something.

What I've done:
- Used bower to install it.
- Included it in Gruntfile.js in the vendors array

``` javascript
    vendor: {
      js: [
        'vendor/angular-bootstrap/ui-bootstrap-tpls.min.js',
        'vendor/placeholders/angular-placeholders-0.0.1-SNAPSHOT.min.js',
        'vendor/angular-ui-utils/modules/route/route.js',
        'vendor/angular-resource/angular-resource.js'
      ]
    },
```
- In reality I've added ngResource as a dependency on a service I'm creating but as a test I added it to `app.js` for simplicity of this issue. Same error occurs in both situations.

``` javascript
angular.module( 'ngBoilerplate', [
  'ngResource',
  'templates-app',
  'templates-component',
  'ngBoilerplate.home',
  'ngBoilerplate.about',
  'ui.route'
])
```

When I run `grunt`, the error `Error: No module: ngResource` occurs.

I'm at a complete loss as I'm sure this is set up in a similar way to how I had it working before. I've confirmed that the angular-resource JS _is_ being included in the final dist but this is still not working. 

Anybody have any insights? Let me know if any other additional information would be useful.

Thanks in advance.

**Comment by joshdmiller** [comment]
@grantlucas I think I know what's happening here. That error is happening during the tests, right? Unfortunately, Karma has its own list of required files in `karma/karma-unit.js` so you'll need to add it there too. If you add it to the `files` array, I'm betting it will magically work.

In v0.3 (which is on the separate branch `v0.3wip`) I've automated this - in addition to adding a bunch of other enhancements. And v0.3 is going live later today!

Anyway, for now, let me know if that fixes it.

**Comment by grantlucas** [comment]
:sob: (tears of joy)

That was definitely the issue. Add that to the list of lessoned learned. It was a combo of _that_ error being thrown and a typo in the resource I was creating that brought the world of pain.

Thanks for the help! I can finally move on :)

**Comment by techterbium** [comment]
I am still seeing this in latest version of ngBoilerplate. And I can see the file listed in karma-unit.js, but still i see the same error. Can some one please help me with this. Stuck with this
