### ISSUE TITLE
Set pageTitle via state object

### ISSUE THREAD

**Issue by timkindberg** [ngbp/ngbp#55]
I had an idea to reduce complexity. Instead of setting page titles in every submodule's controller via titleService, just listen for $stateChangeSuccess in AppCtrl and set the title based on an extra custom `pageTitle` property on each state.

So in app.js controller:

``` javascript
.controller( 'AppCtrl', function AppCtrl ( $scope, $location, titleService ) {
    $scope.$on('$stateChangeSuccess', function(event, toState, toParams, fromState, fromParams){ 
        titleService.setTitle( toState.pageTitle );     
    });
})
```

Then in every state config object, just set pageTitle as a custom property. Custom properties are a smidge frowned upon, we encourage you to put any custom properties into a data property to "namespace" them. Anyway I think its fine.

So you'd do this in home.js config:

``` javascript
.config(function config( $stateProvider ) {
  $stateProvider.state( 'home', {
    url: '/home',
    views: {
      "main": {
        controller: 'HomeCtrl',
        templateUrl: 'home/home.tpl.html'
      }
    },
    pageTitle: "Home"
  });
})
```

Now you can remove all titleService calls in submodule controllers. :)

**Comment by joshdmiller** [comment]
@timkindberg What a great idea! I **love** it. It's easier, clearer, and DRY. If you want to push a PR, I'd totally take it.

One tiny suggestion: I think we should probably put `pageTitle` inside a `data` object to avoid property clashes. It's no big deal in this case, but assuming people are using this as a starting point we might as well encourage them to put any subsequent properties also namespaced in a `data` property by putting this one in there too.

And a question about how this would affect nested states: if we had say "contact" and "contact.filters" where the latter was a modal on the former's page, we may not want to change the page title when its active. Will the child state inherit the `pageTitle` property? I'm thinking that it doesn't. And if it doesn't, perhaps a little check inside your `$on`:

``` js
if ( angular.isDefined( toState.data.pageTitle ) ) {
  titleService.setTitle( toState.data.pageTitle );
}
```

That way we don't have to change the title if we just didn't add that property. What do you think?

Again, great idea. :-)

**Comment by timkindberg** [comment]
Thanks! I'll make up a PR right now. Good point about the nested states I'll test that out.

The data thing just annoys me, I suppose it is the right way to do things. It just feels so lame.

**Comment by ProLoser** [comment]
Why are you guys not doing `<title>{{pageTitle}}</title>`? Having an entire service dedicated to this behavior seems kind of bloated to me.

You could inject $rootScope anywhere you want and just set (or mess with) the pageTitle any way you want.

**Comment by timkindberg** [comment]
@ProLoser good point. I do still like how its attached to the state though kind of.

**Comment by ProLoser** [comment]
I'm not telling you WHERE to put the title-adjustment code, I'm just saying I don't think a service merits the effort required to do it.

**Comment by timkindberg** [comment]
I'm thinking the titleService was originally just used to show an example of where you'd put a common service. And my enhancement just snowballed on that when in reality it needs to be rethought. Perhaps the titleService was really just meant to be deleted after the user looked at and learned from it.

**Comment by timkindberg** [comment]
If @joshdmiller wants to remove titleService in favor of `{{pageTitle}}` I'll leave that up to him. But the pull request has at least removed the junk I added into .gitignore. Thanks for the tip about global, I actually didn't even know that was possible. Looked it up and found a good article. http://devoh.com/blog/2013/01/global-gitignore

**Comment by timkindberg** [comment]
Ok, sorry couldn't help myself. I updated the pull request so that titleService is completely removed. I'm not sure if that's good or bad, like maybe you were using titleService as a teaching tool of what and how a service would be organized and structured in your overall boilerplate architecture. Also it was the only example of coffee compiling. BUT I think ultimately my update is the proper way to do things. So its proper way vs. teaching tool. Up to you! I will not have my feelings hurt regardless.

**Comment by joshdmiller** [comment]
Yeah, the original purposes for the `titleService` were:
1. include a demonstration service (i.e. at least _something_ in `src/common`).
2. avoid requiring setting a `$rootScope` variable.

The latter is important because I don't like scope pollution. It also seems frail; I can change the implementation of the service at any time without affecting its many callers, but the same is not true for a `$rootScope` implementation. So I still think the service was the better way to go, but I allow for a difference of opinion here.

But then we added uiRouter, where it became logical to store the titles themselves within the states...but once the title is the state, it no longer needs the service to set the title cleanly...which made the service unnecessary. Doh!

That's how I like my irony served, my friends. :-)

All things considered, setting this per @ProLoser's suggestion as implemented in your PR is the right solution - I agree. But before I merge it, I need to come up with some other demonstration service. Suggestions?

**Comment by timkindberg** [comment]
Ha, yeah, I figured that was the history of titleService. I'm not sure you need a service just to have one. You don't have a filter, provider, decorator, etc. You do have the plusOne directive. Seems like enough to me as long as the README in common explains that its a place for all those types of things that are common to all projects.

**Comment by ProLoser** [comment]
You should make a concrete `exampleService` for now. I don't think you should stub out services that may lead to people adopting them as status-quo or best practice. If you come up with a better service later you can always change it, but if you start with a service explicitly designated for examples, you could actually add a LOT of different examples into it on some of the different use-cases services solve.

Just an idea.

**Comment by timkindberg** [comment]
Ok, figured it out finally. New PR is submitted, discard the older one. Git makes me feel like an idiot.

> Just attackclone the grit repo pushmerge, then rubygem the lymphnode js shawarma module – and presto!
