### ISSUE TITLE
Add Multiple app support

### ISSUE THREAD

**Issue by sudhakar** [ngbp/ngbp#59]
Hey Josh,

I like your boilerplate and I would love to migrate my current project from brunch.io to ng-boilerplate. But in my project I have 2 single page apps, with each having different app_files config and different index.html files as well.

I tried to run `grunt watch` parallely, but looks like livereload on port 35729 seems to conflict. It would be great if you could add support for multiple single page apps.

And thanx for your great effort.

**Comment by sudhakar** [comment]
Incase if you are ok with this idea, then build.config.js can be

``` js
module.exports = {
  apps: {
    default: {
      build_dir: 'build',
      compile_dir: 'bin',
      app_files: {},
      vendor_files: {}
    },

    app1: {
      build_dir: 'build',
      compile_dir: 'bin',
      app_files: {},
      vendor_files: {}    
    }
  }
}
```

**Comment by joshdmiller** [comment]
@sudhakar - Hello!

I am not sure I follow. If you have two separate HTML files and two separate `app_files` directories, why are they both in the same ngBoilerplate project? Is there a set of code that you're sharing between projects?

To support two separate `app_files` would be pretty complicated I think. While we could just add the configuration, getting all of the many Grunt tasks to do the same thing for two different sources and targets would be tough. I'm not envisioning how I could make that work in a generic way.

**Comment by sudhakar** [comment]
@joshdmiller Yes some of the `js` files and `less` files in the project are shared between two apps. In my case, one app is the main app that is hosted in the site, whereas the second app is a pretty much a trimmed down app with a different `index.html` intended for hosting it in a iframe on our customer's site or as a `tab` in `FB Page`.

Currently ng-boilerplate allows to create only one `ng-boilerplate.js` and one `ng-boilerplate.css` and the names are derived from the app name in package.json. But what I need in my case is something like `app1.js` and `app2.js`

Incase of brunch, I do something like,

``` coffee
  files:
    javascripts:
      joinTo:
        'js/app.js': /^app/
        'js/camp-app.js': ///^(
          app/scripts/camp |
          app/scripts/ext/fields3 |
          app/scripts/ext/misc/services
        )///
```

where app.js includes all js files and camp-app.js includes only a subset.

**Comment by joshdmiller** [comment]
@sudhakar - I think I'm following you, but I don't know how I could implement this generically. Do you have an idea how this can be implemented generically so as not to force anyone else into multiple apps? This might just be something that ngBoilerplate can't support out of the box.

**Comment by sudhakar** [comment]
@joshdmiller Yes josh. I have been mulling over this idea for last couple of days, but couldnt come up with a clean implementation. Will close this for now, until someone wants to open it :)
