### ISSUE TITLE
New files not monitored and processed by grunt watch

### ISSUE THREAD

**Issue by thardy** [ngbp/ngbp#68]
I can change any of the default js or tpl.html files, like home/home.js, or home.tpl.html, and my grunt watch immediately picks up the change and performs the necessary build steps.

If I make any changes to any js files I've created after starting "grunt watch" (say 'new.js'), or any tpl.html files I've created, my grunt watch doesn't see the change and takes no action.  If I re-launch grunt watch, the newer files get monitored.

Should grunt watch be able to monitor newly created js, css, and tpl.html files without having to re-launch it?

**Comment by tschofen** [comment]
What about using grunt-este-watch for this instead?

**Comment by joshdmiller** [comment]
Globs are resolved to individual files when it is first run, and therefore does not include files created thereafter. It should be _possible_ to use a directory-based watch and then use the globs to match tasks to run, but it wouldn't be a simple grunt plugin. While I'll happily consider a PR to implement this, it is an upstream limitation, so I'm going to close this issue.
