### ISSUE TITLE
vendor_files declared twice in concat task

### ISSUE THREAD

**Issue by 0x-r4bbit** [ngbp/ngbp#69]
Right here: https://github.com/joshdmiller/ng-boilerplate/blob/v0.3.0-release/Gruntfile.js#L156-L161

Look like its a duplicate.

**Comment by joshdmiller** [comment]
Yeah, that's no good. That'll certainly bulk up the final package. Good catch, @PascalPrecht!

**Comment by 0x-r4bbit** [comment]
Allright then!

On Mon, Jul 1, 2013 at 10:06 PM, Josh David Miller <notifications@github.com

> wrote:
> 
> Yeah, that's no good. That'll certainly bulk up the final package. Good
> catch, @PascalPrecht https://github.com/PascalPrecht!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joshdmiller/ng-boilerplate/issues/69#issuecomment-20306700
> .

## 

/pp

**Comment by joshdmiller** [comment]
Closed via 09277b7.
