### ISSUE TITLE
Including angular-mocks explicit in karmaConfig task

### ISSUE THREAD

**Issue by 0x-r4bbit** [ngbp/ngbp#70]
Right here: https://github.com/joshdmiller/ng-boilerplate/blob/v0.3.0-release/Gruntfile.js#L393

angular-mocks is declared explicit, a few lines above `<%= vendor_files %>` get included, where angular-mocks should actually already be part of.

Is this just because the task doesn't make sure, that angular-mocks is loaded **after** angularjs ?

**Comment by joshdmiller** [comment]
The reason I chose to include it explicitly is that it is needed in the testing but not in production. If it's in the `vendor_files` it will end up in the distribution, which is not desirable. There should probably be a special testing array inside the `build.config.js` to make this more configurable.

Or did I completely miss what you asked?

**Comment by 0x-r4bbit** [comment]
> There should probably be a special testing array inside the build.config.js to make this more configurable.

That's it!

**Comment by joshdmiller** [comment]
Closed via a04e663.
