### ISSUE TITLE
How to use ng-include files as partials?

### ISSUE THREAD

**Issue by tschofen** [ngbp/ngbp#71]
I'm trying to use an ng-include to load a partial (for the purpose of simplifying the main index.html file.
/div data-ng-include data-src="'src/login/login.tpl.html'"/ also tried
/div data-ng-include data-src="'src/common/login/login.tpl.html'"/

[Discovered that it does include the file as long as it ends in .tpl.html <del>Tried any number of paths until I realized that 'grunt watch' does not pickup the file and copy it. If I copy the files into the correct folder in the build…the app works.</del>]

It adds the file to the template cache, but how do I 'call' it in the index.html file?

Any idea on how to make this work?

**Comment by joshdmiller** [comment]
Yeah, by default anything ending in `.tpl.html` will be added to the template cache, but this is configurable. I'm not sure what you mean by "call it". You should be able to just do:

``` html
<div ng-include="'login/login.tpl.html'"></div>
```

The template paths are normalized from a base path of `src/common` and `src/app` so that part can always be omitted from the template path, as above.

**Comment by tschofen** [comment]
Aha…could it be that the build process doesn't include new folders/files?
After stoping the 'grunt watch' and starting it back up again, it's working.

**Comment by joshdmiller** [comment]
Yeah, unfortunately not. See #68. If this is working for you we can go ahead and close this issue. I hope to find the solution for the watch issue as it's annoying me too.

**Comment by maiphuong** [comment]
I got the same problem and I understood to fixed this issue.We need config in the build.config.js to copy all files under common folder to build/src/common/.Right?

**Comment by joshdmiller** [comment]
@maiphuong Any file ending in `.tpl.html` found anywhere under `src/app` or `src/common` will be included in the template cache; if for some reason you want a different extension, you can add it into the `build.config.js`:

``` js
app_files: {
    // ...
    atpl: [ 'src/app/**/*.tpl.html', 'src/app/**/*.partial.html' ],
    ctpl: [ 'src/common/**/*.tpl.html', 'src/app/**/*.partial.html' ],
    // ...
},
```

**Comment by maiphuong** [comment]
@joshdmiller Thanks.That my fault.I used ng-include="'common/header.tpl.html'".Path is wrong it should be ng-include="'header.tpl.html'".
Thanks,
