### ISSUE TITLE
real simple question from newbie

### ISSUE THREAD

**Issue by ghost** [ngbp/ngbp#72]
Hi,

Can you add to the Getting Started docs on how to add components?  For example...

I want to add the angular-ui/ui-ace (https://github.com/angular-ui/ui-ace) plugin.

I add to bower.js

"angular-ui-ace": "latest"

RUN: bower install

I see the files show up in src/app/components

Now what do i do?

Any help would be great!

**Comment by joshdmiller** [comment]
@johnstontrav - Yeah, that's a good idea. Your problem is the bower configuration, in part. Bower components should _not_ be in into `src/app/components` but in a directory on the root. You should update to v0.3 because there is far better component integration.

But so I can answer your question, what version are you running?

**Comment by ghost** [comment]
@joshdmiller - thanks to accepting my suggestion.  I think im using 0.2.0-SNAPSHOT.  I will upgrade to 0.3 as per your suggestion, so maybe give directions using 0.3 in your reply.  many thanks mate.

-Trav.

**Comment by joshdmiller** [comment]
@johnstontarav - Upgrading is not a simple process, but some instructions can be found in issue #1.

The good news is that once you've updated, the process for added vendor files is really straightforward. Simply `bower install` your component, which installs to `vendor/`, and then add the file(s) you want to include to the `vendor.js` array in `build.config.js`.

**Comment by ghost** [comment]
@joshdmiller I am not that far into my project, so I can do a fresh install and add my code.  Yay.

Thanks for the instructions.  Am I right to assume any vender CSS files get added to the main.less file?

**Comment by joshdmiller** [comment]
@johnstontrav I totally neglected this; sorry. Unfortunately CSS files are not automatically added to the build. See issue #65. 

Since it sounds like your core problem is resolved, I'm going to close this issue.
