### ISSUE TITLE
Adding assets from vendor directory - adding font-awesome locally

### ISSUE THREAD

**Issue by tschofen** [ngbp/ngbp#74]
In the process of moving font-awsome locally, I can't figure out how to change the grunt file that it moves the font directory from the vendor directory into the assets folder on build and compile.

I tried adding the path to the assets
      assets: {
        files: [ 
          'src/assets/*_/_',
          'vendor/font-awesome/font/*'
        ],
        tasks: [ 'copy:build_assets' ]
      },

Then I tried changing the copy task:
    copy: {
      build_assets: {
        files: [
          { 
            src: [ '*_' ],
            dest: '<%= build_dir %>/assets/',
            cwd: 'src/assets',
            expand: true
          },
          { 
            src: [ 'vendor/font-awesome/font/_' ],
            dest: '<%= build_dir %>/assets/',
            cwd: 'src/assets',
            expand: true
          }
       ]  
      },

Neither of these works. Any idea how I can get this to work, so I don't have to copy the font into the assets folder/

**Comment by timhaak** [comment]
How i solved this

bower install font-awesome

edit src/less/main.less and add
  @import "../../vendor/font-awesome/less/font-awesome.less";

edit build.config.js

vendor_files: {
        js: [
            'vendor/jquery/jquery.js',
            'vendor/angular/angular.js',
            'vendor/angular-bootstrap/ui-bootstrap-tpls.min.js',
            'vendor/placeholders/angular-placeholders-0.0.1-SNAPSHOT.min.js',
            'vendor/angular-ui-router/release/angular-ui-router.js',
            'vendor/angular-ui-utils/modules/route/route.js',
            'vendor/ng-grid/build/ng-grid.js',
            'vendor/sjcl/sjcl.js'
        ],
        css: [
            'vendor/ng-grid/ng-grid.css'
        ],
        font: [
            'vendor/font-awesome/font/*'
        ]

```
}
```

edit Grunt.js

,
            build_vendor_font: {
                files: [
                    {
                        src: [ '<%= vendor_files.font %>' ],
                        dest: '<%= build_dir %>/font/',
                        flatten: true,
                        cwd: '.',
                        expand: true
                    }
                ]
            }

,
            compile_font: {
                files: [
                    {
                        src: [ '**' ],
                        dest: '<%= compile_dir %>/font',
                        cwd: '<%= build_dir %>/font',
                        expand: true
                    }
                ]
            }

Add required registerTask

**Comment by joshdmiller** [comment]
This should be supported, albeit a little differently, as of 29502bff8eb649501945aef37fe50d81c36151ba. It will be merged as part of v0.3.1 in just a little while.

**Comment by jboothe** [comment]
I just implemented the solution in this post. You hinted at a slightly different solution. I don't see it in 0.3.1. Any change?

**Comment by joshdmiller** [comment]
@jboothe It is part of 0.3.1; see the Changelog for a link to the commit. What specifically are you not seeing?

**Comment by mbroadst** [comment]
I see that you can include the fonts in build.conf.js under "assets" (I suppose this is what you meant by the "different" approach to support this above), however the fontawesome.less file includes the fonts with a prefix: "../fonts/". How would you go about fixing this in the build process?

**Comment by andreeib** [comment]
@mbroadst You can overwrite the Font Awesome path using a less variable:

```
@fa-font-path:   "/assets/";
```

**Comment by mbroadst** [comment]
@andreeib yes I ended up getting that far, but I could never actually get the page to download the fonts. Do you actually have this working completely?

**Comment by andreeib** [comment]
@mbroadst Yes, It's working great for me on multiple projects.

**Comment by jrzerr** [comment]
These instructions were very helpful after piecing some together.

Having an absolute url in the `@fa-font-path: "/assets/";` variable can be done in a different way for better portability by doing:

```
@fa-font-path: "../assets";
```

I made this addition to my `src/less/variables.less` file.

Rest of the solution was doing `bower install font-awesome --save-dev` which put font-awesome in my vendor directory.

Then in `build.config.js` in vendor_files.assets, set it like this:

```
    assets: [
        'vendor/font-awesome/fonts/*'
    ]
```

Notice the change from `font` to `fonts` that differs from some comments above.

I really wish I didn't have to undo this, seems much better to have font awesome included locally instead of via CDN as the default setting in ngbp.

**Comment by manichandra** [comment]
@timhaak  awesome. it was very useful . I have used it to get bootstrap glyphicons. 

---

build.config.js

```
vendor_files: {
js: [
  'vendor/angular/angular.js',
  'vendor/angular-bootstrap/ui-bootstrap-tpls.min.js',
  'vendor/placeholders/angular-placeholders-0.0.1-SNAPSHOT.min.js',
  'vendor/angular-ui-router/release/angular-ui-router.js',
  'vendor/angular-ui-grid/ui-grid.js',
  'vendor/angular-ui-utils/modules/route/route.js'
],
css: [
      'vendor/angular-ui-grid/ui-grid.css'
],
font: [
      /*'vendor/font-awesome/font/!*',*/
      'vendor/bootstrap/fonts/*'

],
assets: [
    'vendor/angular-ui-grid/ui-grid.ttf',
    'vendor/angular-ui-grid/ui-grid.svg',
    'vendor/angular-ui-grid/ui-grid.woff'

 ]
 }
```

   };

---

gruntfile.js 

```
build_vendor_font: {
    files: [
      {
        src: [ '<%= vendor_files.font %>' ],
        dest: '<%= build_dir %>/fonts/',
        flatten: true,
        cwd: '.',
        expand: true
      }
    ]
  },
  compile_font: {
    files: [
      {
        src: [ '**' ],
        dest: '<%= compile_dir %>/fonts',
        cwd: '<%= build_dir %>/fonts',
        expand: true
      }
    ]
  },
```
