### ISSUE TITLE
ng-grid

### ISSUE THREAD

**Issue by jonmat** [ngbp/ngbp#76]
First off, I really like the work you've done here. Being a newbie developing for the client, I appreciate all that's gone into ngBoilerplate--Good on ya!

My first attempt to see how far I could go with ngBoilerplate was to see if I could integrate a simple ng-grid example. 

As indicated in tools.md, bower plucked the ng-grid and jquery components, but I am having difficulty understanding the extent of the required dependencies past that point. I believe I've correctly added into my ngBoilerplate project the js and css references for ng-grid and jquery, but the simple grid example has no formatting, though the data does appear.

Viewing the source for ng-grid's example page, at http://angular-ui.github.io/ng-grid/, I see that they've thrown in the proverbial kitchen sick, including all kinds of js frameworks. It seems that some of these frameworks would collide with the intended mix of frameworks chosen for ngBoilerplate.

1st question) Is there an easy way to derive precisely which additional dependencies are required for a new component added to ngBoilerplate and downloaded with bower?

2nd question) Do I need to worry about components stepping on each other, in particular with the base-mix chosen for ngBoilerplate?

3rd question) Do you happen to know if ng-grid will work with ngBoilerplate, as in, has there been a successful integration of the two?

cheers!

**Comment by jonmat** [comment]
I did manage to make ngGrid work with ngBoilerplate. Turns out less's @import will not import css files.

**Comment by jenzweben** [comment]
Hi there - I'm a novice with angularjs and I'm trying to get ng-grid to work.  Can you let me know what you had to change to get it to work?  Right now I'm just trying to get the ng-grid example to work...I tried with angular-seed and ngbp but no luck...any help you can provide would be greatly appreciated!

**Comment by PaulL1** [comment]
I did ng-grid in my ngpb-based tutorial, which can be found at: http://technpol.wordpress.com/2013/11/09/angularjs-and-rails-4-crud-application-using-ng-boilerplate-and-twitter-bootstrap-3-tutorial-index/

It has some rails bits, but you can probably skip most of that and just use the angular bits.  The actual ng-grid bits of the tutorial are in part 6: http://technpol.wordpress.com/2013/11/17/6-adding-nggrid-and-an-edit-page/
