### ISSUE TITLE
Why not make this project a Yeoman generator?

### ISSUE THREAD

**Issue by dearfrankg** [ngbp/ngbp#77]
http://yeoman.io/index.html

**Comment by joshdmiller** [comment]
I've considered it, but I'm not sure its worth the effort just to get some scaffolding. It is, after all, quite a big undertaking. If someone in the community wants to explore doing this, I would be open to reviewing the changes, but at present I don't have the time to do the coding myself.

That said, I started conversations a few months ago with the generator-angular team at yeoman to make it more like ngBoilerplate: yeoman/generator-angular#109.

**Comment by joshdmiller** [comment]
I'll go ahead and close this issue, but if anyone wants to tackle the task I'd be happy to reopen it.

**Comment by kvnwolf** [comment]
I've started working on this generator.
Take a look and suggest features https://github.com/kevin-wolf/generator-ngbp ;).

**Comment by dhuyvetter** [comment]
What about this one? https://github.com/thardy/generator-ngbp

I'm trying it out now and seems quite good.
