### ISSUE TITLE
possible missing in Gruntfile.js

### ISSUE THREAD

**Issue by ghost** [ngbp/ngbp#81]
Hi,

I had to add this to the Gruntfile.js to get the vender css files to be moved.

'<%= vendor_files.css %>'

so now my complete array is...

build_vendorjs: {
                files: [
                    {
                        src: [ '<%= vendor_files.js %>','<%= vendor_files.css %>' ],
                        dest: '<%= build_dir %>/',
                        cwd: '.',
                        expand: true
                    }
                ]
            },

I am new to git so don't know how to submit this in a formal way.

**Comment by joshdmiller** [comment]
Yeah, this was an oversight on my part. There are open issues for this already (#57 and #65) so I'll go ahead and close this one.
