### ISSUE TITLE
using ui dialog with views

### ISSUE THREAD

**Issue by stanrogo** [ngbp/ngbp#87]
Currently I am getting round this problem by putting html files in the assets folder, however this definitely isn't the way to do it.

Maybe I'm being a tad naive here but...

The ui dialog requires that a templateUrl be present from which it can load it's contents. Unfortunately the templates are compiled into one single file right now. SO how do I get around the fact that I can otherwise not use my templates as I cannot reference them by a path?

**Comment by joshdmiller** [comment]
You absolutely _can_ reference them by path. The path is relative to `src/app/` or `src/common/`. For example, if you have a view template in `src/app/editor/settingsDialog.tpl.html`, then you pass to uiDialog: `templateUrl: "editor/settingsDialog.tpl.html"`. This will work for all components that ask for a template, including ngInclude.

Sorry this is so late. :-(
