### ISSUE TITLE
build/README.md gone

### ISSUE THREAD

**Issue by RichardLitt** [ngbp/ngbp#89]
Not sure if this is intentional or not, but there's a link to a build/README.md in the main README, and there's no build/ folder available. 

Broken link: 
https://github.com/joshdmiller/ng-boilerplate/blob/v0.3.0-release/build/README.md

**Comment by RichardLitt** [comment]
May have spoken too soon - I see a build folder is created when the thing is installed using the commands in the docs for a quick start. Still no README, though.

**Comment by joshdmiller** [comment]
It's an error in the readme. We'll get this fixed in the next release.

**Comment by joshdmiller** [comment]
Closed via fbb9263.
