### ISSUE TITLE
app.coffee does not work

### ISSUE THREAD

**Issue by Claus1** [ngbp/ngbp#91]
I tested coffeescript support and replaced app.js by app.coffeescript analogue

angular.module("ngBoilerplate", ["templates-app", "templates-common", "ngBoilerplate.home", "ngBoilerplate.about", "ui.state", "ui.route"]).config(($stateProvider, $urlRouterProvider) ->
  $urlRouterProvider.otherwise "/home"
).run((titleService) ->
  titleService.setSuffix " | ngBoilerplate"
).controller "AppCtrl", ($scope, $location) ->

The build system says now:
...
Running "jshint:gruntfile" (jshint) task

> > 1 file lint free.

Running "jshint:globals" (jshint) task

> > 0 files linted. Please check your ignored files.

Process finished with exit code 3

Where is the problem? and why?

**Comment by joshdmiller** [comment]
Did you get your issue solved?

**Comment by Claus1** [comment]
No.

2013/8/6 Josh David Miller notifications@github.com

> Did you get your issue solved?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joshdmiller/ng-boilerplate/issues/91#issuecomment-22152889
> .

## 

Best regards, Georgii Dernovyi

**Comment by joshdmiller** [comment]
Can you try to clean up the code in your post (it's a little hard to read)
as well as post the full `grunt default` output?

**Comment by Claus1** [comment]
``` coffeescript
angular.module("ngBoilerplate", ["templates-app",
  "templates-common",
  "ngBoilerplate.home",
  "ngBoilerplate.about",
  "ui.state",
  "ui.route"]).
config(($stateProvider, $urlRouterProvider) ->
  $urlRouterProvider.otherwise "/home"
).run((titleService) ->
  titleService.setSuffix " | ngBoilerplate"
).controller "AppCtrl", ($scope, $location) -> 
```

now gets

Running "recess:compile" (recess) task
File "build/assets/ui.css" created.
Uncompressed size: 61125 bytes.
Compressed size: 7304 bytes gzipped (49452 bytes minified).

Running "copy:compile_assets" (copy) task
Created 6 directories, copied 29 files

Running "ngmin:compile" (ngmin) task
ngminifying build/src/app/about/about.js, build/src/app/app.js, build/src/app/ho
me/home.js, build/src/common/plusOne/plusOne.js, build/src/common/titleService/t
itleService.js

Running "concat:compile_js" (concat) task
Warning: An error occurred while processing a template (Cannot read property 'ty
pe' of undefined). Use --force to continue.

Aborted due to warnings.

:)

**Comment by joshdmiller** [comment]
Can you confirm that the compiled version exists in `build/src/`?

**Comment by Claus1** [comment]
Yes, it exists and works.

2013/8/9 Josh David Miller notifications@github.com

> Can you confirm that the compiled version exists in build/src/?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joshdmiller/ng-boilerplate/issues/91#issuecomment-22375457
> .

## 

Best regards, Georgii Dernovyi

**Comment by joshdmiller** [comment]
Hmm. Can you try with `--verbose --debug` to see if we get a better error
message?

**Comment by Claus1** [comment]
I tried and got

...
Running "concat" task
[D] Task source:
c:\MyProjects\aboilerplate\node_modules\grunt-contrib-concat\ta
sks\concat.js

Running "concat:compile_js" (concat) task
[D] Task source:
c:\MyProjects\aboilerplate\node_modules\grunt-contrib-concat\ta
sks\concat.js
Verifying property concat.compile_js exists in config...Warning: An error
occurr
ed while processing a template (Cannot read property 'type' of undefined).
Use -
-force to continue.

Aborted due to warnings.

2013/8/9 Josh David Miller notifications@github.com

> Hmm. Can you try with `--verbose --debug` to see if we get a better error
> message?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joshdmiller/ng-boilerplate/issues/91#issuecomment-22378483
> .

## 

Best regards, Georgii Dernovyi

**Comment by jingman** [comment]
I was having this same issue, and it turned out to be a change I had made to `package.json`.

Make sure that any code getting processed as a Grunt template is error-free. The original `meta.banner` string [included in ng-boilerplate](https://github.com/joshdmiller/ng-boilerplate/blob/v0.3.0-release/Gruntfile.js#L44) uses a lot of `<%= pkg.foo %>` variables, and if you remove any of them from your `package.json`, (I had removed the licenses) you will get an error during the compile task. My `grunt --verbose --debug` output was...

```
Running "concat:compile_js" (concat) task
[D] Task source: ../node_modules/grunt-contrib-concat/tasks/concat.js
Verifying property concat.compile_js exists in config...Warning: An error occurred while processing a template (Cannot read property 'type' of undefined). Use --force to continue.
```

**Comment by 27leaves** [comment]
Had the same issue, you had the correct hint @jingman! Thanks!

**Comment by joshdmiller** [comment]
@jingman Yeah, Grunt template error reporting needs a little improvement.

@Claus1 Does this help?

**Comment by aphexddb** [comment]
Huge help @jingman

**Comment by roymilder** [comment]
Thanks @jingman

**Comment by simonsheridan** [comment]
@Claus1 any update on your error?  I am considering writing some of my components in coffeescript and would like to know if the grunt-contrib-concat package has issues with compiled coffeescript.  Are you using coffeescript in your template file?  Does anyone know what went wrong here?

**Comment by Claus1** [comment]
@simonsheridan I don't know. I use angular-fun which optimized for Coffee.

**Comment by simonsheridan** [comment]
@Claus1 That looks neat but I think I prefer the folder grouping by functionality structure of ngbp.  I'll play around with using coffee and see what happens.  Thanks for the suggestion!

**Comment by marcmenges** [comment]
Thanks @jingman
