### ISSUE TITLE
When executing "grunt watch", it aborts due to warnings.

### ISSUE THREAD

**Issue by ferrlin** [ngbp/ngbp#92]
Hello,

This is what I end up getting after following the guide for running ng-boilerplate.

> Running "karmaconfig:unit" (karmaconfig) task
> 
> Running "karma:continuous" (karma) task
> WARN [config]: config.configure() is deprecated, please use config.set() instead.
> INFO [karma]: Karma v0.9.5 server started at http://localhost:9018/
> INFO [launcher]: Starting browser Firefox
> ERROR [launcher]: Cannot start Firefox
>   Can not find the binary /Applications/Firefox.app/Contents/MacOS/firefox-bin
>   Please set env variable FIREFOX_BIN
> Warning: Task "karma:continuous" failed. Use --force to continue.
> 
> Aborted due to warnings.

Any idea what's the problem? Thanks.

Here are some info about the version of the tools used:

> bower : 1.0.0
> karma: 0.8.7
> grunt-cli: 0.1.9
> grunt: 0.4.1

**Comment by ferrlin** [comment]
The issue was fixed by installing firefox.

**Comment by nousename** [comment]
that does not really fix the problem !
grunt and the ng-boilerplate are on my server - no firefox installed, and not going to be either.
why is it a requirement ?
I'm viewing the boilerplate in chrome on anther machine.
having now to user grunt watch --force
which seems somewhat unecessary

**Comment by PaulL1** [comment]
It's not a requirement, you can edit your Karma config to use PhantomJS instead (you'd need to install PhantomJS).  

If you really don't want to unit test (not recommended), then issue #204 provides guidance on turning off Karma.

**Comment by joshdmiller** [comment]
@nousename If you're testing from another machine, you can also do the unit tests from there too. Just empty the browser string in your Karma config and open port `9101` on your server. From wherever you're looking at the code, go to `servername:9101` when you run the tests and it will all work. But @PaulL1's suggestion of PhantomJS is probably better (and it's installed by default in ngbp).

But this is very non-standard and not recommended. A `watch` is for local development. I'm not sure why you're developing remotely, but as it's a non-standard use case, ngbp won't be supporting it - at least not without a pull request.

**Comment by PaulL1** [comment]
When I develop on my Linux server (usually I'm on my Macbook) my development server is a virtual.  I NFS mount the file system so my editor can get at the virtual, and I run all the testing etc headless on the linux server.  No really good reason for doing that - when I started I was on a Windows laptop that I didn't want to try to get the dev tools working on, but I wanted to use the laptop for the editor.  That setup stayed the same when I moved to developing on the server.

Anyway, on that machine I do as @joshdmiller suggests, I empty the browser setting from the karma config, then I run a local browser instance that connects to server:9101, and it uses that for the testing.  I need a browser to test that application manually anyway, so it's not that big a deal to open an extra tab and connect to 9101. (Although my port is actually 9108 for build, and sometimes 9109 for watch, which I haven't bothered to fix, so something to watch out for).

**Comment by maxfelker** [comment]
As a note for any person trying to figure this out, here are the steps to update your project to use Phantomjs. This was done on my mac book pro:

**Install Phantom JS**
`brew install phantomjs`

**Install Karma Phantom JS plugin**
`npm install karma-phantomjs-launcher --save-dev`

[See docs on github](https://github.com/karma-runner/karma-phantomjs-launcher)

_Edit Karma config_
Add the following plugin to the Karma config found at `karma/karma-util.tpl.js` on line 21:

```
plugins: [ 'karma-jasmine', 'karma-firefox-launcher', 'karma-coffee-preprocessor', 'karma-phantomjs-launcher' ],
```

Updated browser on line 57:

```
browsers: [
  'PhantomJS'
]
```

Edited: I don't understand why Firefox is the default and feel like that's a bad decision to use a browser as default. I see that you can set it up to use different browsers but that just seems wonky to me. If this is going to be a requirement, it should be explicitly outlined in the read me because I had to search around to get it to work.
