### ISSUE TITLE
Setup Issue - missing Karma plugins

### ISSUE THREAD

**Issue by perqa** [ngbp/ngbp#93]
I am trying to install ng-boilerplate according to the instructions, but I get a bunch of warnings in the last step of the setup, "grunt watch". 

As I already had Karma installed, I only installed grunt-cli and bower, thus omitting karma from the npm -g install command  given in the instructions. When I got the warnings below, I reinstalled Karma, but that didn't make any difference at all. 

> grunt watch
> ........
> Running "karma:continuous" (karma) task
> WARN [config]: config.configure() is deprecated, please use config.set() instead.
> WARN [plugin]: Cannot find plugin "karma-jasmine".
>   Did you forget to install it ?
>   npm install karma-jasmine --save-dev
> WARN [plugin]: Cannot find plugin "karma-firefox-launcher".
>   Did you forget to install it ?
>   npm install karma-firefox-launcher --save-dev
> WARN [plugin]: Cannot find plugin "karma-chrome-launcher".
>   Did you forget to install it ?
>   npm install karma-chrome-launcher --save-dev
> WARN [plugin]: Cannot find plugin "karma-coffee-preprocessor".
>   Did you forget to install it ?
>   npm install karma-coffee-preprocessor --save-dev
> Warning: No provider for "framework:jasmine"! (Resolving: framework:jasmine) Use --force to continue.

Aborted due to warnings.

**Comment by perqa** [comment]
Just realized this is the same as issue 58: https://github.com/joshdmiller/ng-boilerplate/issues/58. I will upgrade Node to the latest version and try again.

**Comment by joshdmiller** [comment]
I'll go ahead and close this issue, but please let us know if you're still having trouble.
