### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by perqa** [ngbp/ngbp#94]
Running the command 
sudo npm -g install grunt-cli karma bower
produces the following errors:

Debug Log: https://docs.google.com/file/d/0BwV7xb-E6LSNU2MwN0ZnakxwMmc/edit?usp=sharing

```
> ws@0.4.27 install /usr/local/lib/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
/usr/local/bin/karma -> /usr/local/lib/node_modules/karma/bin/karma
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/couch-login requires request@'~2.9.202' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/request,
npm WARN unmet dependency which is version 2.21.0
npm ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma-jasmine@0.0.3 wants karma@~0.9

npm ERR! System Darwin 11.4.2
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "grunt-cli" "karma" "bower"
npm ERR! cwd /Users/per/Workspace/ng-boilerplate
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/per/Workspace/ng-boilerplate/npm-debug.log
npm ERR! not ok code 0
```

**Comment by ElliotPsyIT** [comment]
First check your version of Node `node --version`.  You need version 0.8.19 or higher for npm to mange the peerDependencies that karma uses (notice this error above).

`npm ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!`

**Comment by perqa** [comment]
Thanks for the reply. The versions of node and npm were actually in my previous post, but maybe a bit hard to find in that log file extract:
node -v v0.10.13
npm -v 1.3.2

**Comment by ElliotPsyIT** [comment]
D'oh - of course it's there!  Apologies.

Next step is checking your version of karma.  The error message referencing the invalid peer specifies a requirement based on the plugin karma-jasmine - `Peer karma-jasmine@0.9.3 wants karma@~0.9`.  karma-jasmine comes packaged with karma.  It's own peerDependencies require a minimum version of karma, as below:

``` },
  "peerDependencies": {
    "karma": ">=0.9"
  },
```

Is your version of karma at least 0.9?

**Comment by perqa** [comment]
Aha, you might be on to something there: my Karma version: 0.8.7. Current version: 0.10.0 (last updated 9 hours ago). The weird thing is that I did install Karma at the same time as grunt-cli and bower two weeks ago using 
sudo npm -g install grunt-cli karma bower

**Comment by joshdmiller** [comment]
@perqa Did you get your issue solved?

**Comment by perqa** [comment]
Thanks for asking. Unfortunately not. Trying to install karma (to update it
to the latest version) results in all these plugins complaining it's an old
version... It's a catch 22:

npm WARN unmet dependency
/usr/local/lib/node_modules/npm/node_modules/couch-login requires
request@'~2.9.202'
but will load
npm WARN unmet dependency
/usr/local/lib/node_modules/npm/node_modules/request,
npm WARN unmet dependency which is version 2.21.0
npm ERR! peerinvalid The package karma does not satisfy its siblings'
peerDependencies requirements!
npm ERR! peerinvalid Peer karma-chrome-launcher@0.1.0 wants karma@>=0.9.3
npm ERR! peerinvalid Peer karma-coffee-preprocessor@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-firefox-launcher@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-html2js-preprocessor@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-jasmine@0.0.3 wants karma@~0.9
npm ERR! peerinvalid Peer karma-phantomjs-launcher@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-requirejs@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-script-launcher@0.1.0 wants karma@>=0.9

npm ERR! System Darwin 11.4.2
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g"
"karma"
npm ERR! cwd /Users/per/Workspace
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/per/Workspace/npm-debug.log
npm ERR! not ok code 0

/Per Q A

**Comment by joshdmiller** [comment]
@perqa I just ran into the same problem. The solution is to remove `node_modules/` and run `npm cache clear` (globally too) and then to install the latest version of grunt-karma with `npm install --save-dev grunt-karma@0.7.1`. You may also need to uninstall all those karma plugins globally and reinstall karma globally.

**Comment by joshdmiller** [comment]
I'll go ahead and close it. If the above solution doesn't work for you, let me know and we'll reopen it.

**Comment by perqa** [comment]
Thanks for the notification and advice. Sorry I haven't replied earlier.
Tracking down all those Karma plugins to uninstall them seemed like a
daunting task. How do I find them all? Anyway, I will start with the easy
part and hopefully that's enough.

All the Best,
Per Q A

**Comment by richardwardza** [comment]
The 'local' ones should be removed when you remove the node_modules directory.
The global ones I think can be removed by _unsafe_ deleteing them out /usr/local/lib/node_modules/ or perhaps better would be "npm ls -g" and then "npm uninstall [module name] -g"

I haven't tried the 'remove directory' option before so I' not sure if that is correct but this could at least help get you started in looking for more info.

**Comment by joshdmiller** [comment]
Definitely remove them safely per @richardwardza's instructions. Try `npm ls -g | grep karma` and then removing all of those with `npm uninstall -g [list of all modules here]`. You may have to alter the order of some if it complains about dependencies, but it should only take a couple of minutes total.

But locally, you can just remove the `node_modules/` directory.

**Comment by perqa** [comment]
Ok, thanks for the clarification. Very valuable information for me.

/Per Q A
