### ISSUE TITLE
After upgrade to 0.3.0: Karma error: "Can not load 'PhantomJS', it is not registered!"

### ISSUE THREAD

**Issue by rickhuizinga** [ngbp/ngbp#96]
After upgrading to ng-boilerplate 0.3.0, with its updated dependency on grunt-karma 0.5.0, the grunt process stops with a Karma warning: "Can not load 'PhantomJS', it is not registered!".

The problem is that the plugins line of karma-unit.tpl.js only has 'karma-firefox-launcher' and 'karma-chrome-launcher'.  Updating it to add 'karma-phantomjs-launcher' will fix the problem.

**Comment by joshdmiller** [comment]
@rickhuizinga Good catch - you're right; PhantomJS should be included as well. Would you be so kind as to submit a PR? :-)

**Comment by rickhuizinga** [comment]
I just submitted pull request #109

**Comment by joshdmiller** [comment]
Closed by dda8792c57bdb1544c01f2dc1c8873ac264ff6c1.
