### ISSUE TITLE
ng-boilerplate on a server, no firefox- karma complains?

### ISSUE THREAD

**Issue by JessicaMulein** [ngbp/ngbp#98]
I'm totally new to MEAN/grunt/karma/ng-boilerplate and I've got ng boilerplate checked out on a server, and it wants to run firefox which I don't have on purpose. What's the usual procedure/setup for a server so that grunt/karma are happy?

**Comment by joelhooks** [comment]
https://github.com/joshdmiller/ng-boilerplate/blob/v0.3.0-release/karma/karma-unit.tpl.js

line 56, you can add/remove browsers as appropriate. PhantomJS is popular when you need to run headless.

**Comment by JessicaMulein** [comment]
Thanks for pointing me in the right direction.
